/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator.tables.records;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMsgSubs;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxWxMsgSubsRecord extends UpdatableRecordImpl<FxWxMsgSubsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_wx_msg_subs.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_wx_msg_subs.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_wx_msg_subs.OPEN_ID</code>.
     */
    public void setOpenId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_wx_msg_subs.OPEN_ID</code>.
     */
    public String getOpenId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fx.fx_wx_msg_subs.TEMPLATE_ID</code>.
     */
    public void setTemplateId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_wx_msg_subs.TEMPLATE_ID</code>.
     */
    public String getTemplateId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_wx_msg_subs.COUNT</code>.
     */
    public void setCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_wx_msg_subs.COUNT</code>.
     */
    public Integer getCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fx.fx_wx_msg_subs.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_wx_msg_subs.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fx.fx_wx_msg_subs.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_wx_msg_subs.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxWxMsgSubsRecord
     */
    public FxWxMsgSubsRecord() {
        super(FxWxMsgSubs.FX_WX_MSG_SUBS);
    }

    /**
     * Create a detached, initialised FxWxMsgSubsRecord
     */
    public FxWxMsgSubsRecord(Long id, String openId, String templateId, Integer count, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxWxMsgSubs.FX_WX_MSG_SUBS);

        setId(id);
        setOpenId(openId);
        setTemplateId(templateId);
        setCount(count);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxWxMsgSubsRecord
     */
    public FxWxMsgSubsRecord(com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs value) {
        super(FxWxMsgSubs.FX_WX_MSG_SUBS);

        if (value != null) {
            setId(value.getId());
            setOpenId(value.getOpenId());
            setTemplateId(value.getTemplateId());
            setCount(value.getCount());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
