/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator.tables.records;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMessage;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxWxMessageRecord extends UpdatableRecordImpl<FxWxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_wx_message.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_wx_message.OPEN_ID</code>.
     */
    public void setOpenId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.OPEN_ID</code>.
     */
    public String getOpenId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fx.fx_wx_message.TEMPLATE_ID</code>.
     */
    public void setTemplateId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.TEMPLATE_ID</code>.
     */
    public String getTemplateId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_wx_message.PAGE</code>.
     */
    public void setPage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.PAGE</code>.
     */
    public String getPage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fx.fx_wx_message.MSG_BODY</code>.
     */
    public void setMsgBody(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.MSG_BODY</code>.
     */
    public String getMsgBody() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fx.fx_wx_message.STATUS</code>.
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.STATUS</code>.
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>fx.fx_wx_message.FAIL_MSG</code>.
     */
    public void setFailMsg(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.FAIL_MSG</code>.
     */
    public String getFailMsg() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fx.fx_wx_message.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>fx.fx_wx_message.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>fx.fx_wx_message.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxWxMessageRecord
     */
    public FxWxMessageRecord() {
        super(FxWxMessage.FX_WX_MESSAGE);
    }

    /**
     * Create a detached, initialised FxWxMessageRecord
     */
    public FxWxMessageRecord(Long id, String openId, String templateId, String page, String msgBody, Integer status, String failMsg, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxWxMessage.FX_WX_MESSAGE);

        setId(id);
        setOpenId(openId);
        setTemplateId(templateId);
        setPage(page);
        setMsgBody(msgBody);
        setStatus(status);
        setFailMsg(failMsg);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxWxMessageRecord
     */
    public FxWxMessageRecord(com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage value) {
        super(FxWxMessage.FX_WX_MESSAGE);

        if (value != null) {
            setId(value.getId());
            setOpenId(value.getOpenId());
            setTemplateId(value.getTemplateId());
            setPage(value.getPage());
            setMsgBody(value.getMsgBody());
            setStatus(value.getStatus());
            setFailMsg(value.getFailMsg());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
