/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.pay.dal.generator.tables.records;


import com.iqexception.fxhelper.pay.dal.generator.tables.FxPayInfo;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxPayInfoRecord extends UpdatableRecordImpl<FxPayInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_pay_info.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_pay_info.FROM_CHANNEL</code>.
     */
    public void setFromChannel(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.FROM_CHANNEL</code>.
     */
    public Integer getFromChannel() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fx.fx_pay_info.FROM_ACCOUNT</code>.
     */
    public void setFromAccount(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.FROM_ACCOUNT</code>.
     */
    public String getFromAccount() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_pay_info.FROM_TRX_ID</code>.
     */
    public void setFromTrxId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.FROM_TRX_ID</code>.
     */
    public String getFromTrxId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fx.fx_pay_info.TO_CHANNEL</code>.
     */
    public void setToChannel(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.TO_CHANNEL</code>.
     */
    public Integer getToChannel() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>fx.fx_pay_info.TO_ACCOUNT</code>.
     */
    public void setToAccount(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.TO_ACCOUNT</code>.
     */
    public String getToAccount() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fx.fx_pay_info.TO_TRX_ID</code>.
     */
    public void setToTrxId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.TO_TRX_ID</code>.
     */
    public String getToTrxId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fx.fx_pay_info.BIZ_ID</code>.
     */
    public void setBizId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.BIZ_ID</code>.
     */
    public String getBizId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fx.fx_pay_info.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>fx.fx_pay_info.STATUS</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fx.fx_pay_info.PAY_ACCT_INFO</code>.
     */
    public void setPayAcctInfo(JSON value) {
        set(10, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.PAY_ACCT_INFO</code>.
     */
    public JSON getPayAcctInfo() {
        return (JSON) get(10);
    }

    /**
     * Setter for <code>fx.fx_pay_info.RECV_ACCT_INFO</code>.
     */
    public void setRecvAcctInfo(JSON value) {
        set(11, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.RECV_ACCT_INFO</code>.
     */
    public JSON getRecvAcctInfo() {
        return (JSON) get(11);
    }

    /**
     * Setter for <code>fx.fx_pay_info.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>fx.fx_pay_info.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>fx.fx_pay_info.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxPayInfoRecord
     */
    public FxPayInfoRecord() {
        super(FxPayInfo.FX_PAY_INFO);
    }

    /**
     * Create a detached, initialised FxPayInfoRecord
     */
    public FxPayInfoRecord(Long id, Integer fromChannel, String fromAccount, String fromTrxId, Integer toChannel, String toAccount, String toTrxId, String bizId, BigDecimal amount, String status, JSON payAcctInfo, JSON recvAcctInfo, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxPayInfo.FX_PAY_INFO);

        setId(id);
        setFromChannel(fromChannel);
        setFromAccount(fromAccount);
        setFromTrxId(fromTrxId);
        setToChannel(toChannel);
        setToAccount(toAccount);
        setToTrxId(toTrxId);
        setBizId(bizId);
        setAmount(amount);
        setStatus(status);
        setPayAcctInfo(payAcctInfo);
        setRecvAcctInfo(recvAcctInfo);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxPayInfoRecord
     */
    public FxPayInfoRecord(com.iqexception.fxhelper.pay.dal.generator.tables.pojos.FxPayInfo value) {
        super(FxPayInfo.FX_PAY_INFO);

        if (value != null) {
            setId(value.getId());
            setFromChannel(value.getFromChannel());
            setFromAccount(value.getFromAccount());
            setFromTrxId(value.getFromTrxId());
            setToChannel(value.getToChannel());
            setToAccount(value.getToAccount());
            setToTrxId(value.getToTrxId());
            setBizId(value.getBizId());
            setAmount(value.getAmount());
            setStatus(value.getStatus());
            setPayAcctInfo(value.getPayAcctInfo());
            setRecvAcctInfo(value.getRecvAcctInfo());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
