/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.order.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OrderDetail
 */
@JsonPropertyOrder({
  OrderDetail.JSON_PROPERTY_ID,
  OrderDetail.JSON_PROPERTY_SHOP_ID,
  OrderDetail.JSON_PROPERTY_USER_ID,
  OrderDetail.JSON_PROPERTY_CAPTURE,
  OrderDetail.JSON_PROPERTY_AMOUNT,
  OrderDetail.JSON_PROPERTY_FX_TIME,
  OrderDetail.JSON_PROPERTY_STATUS,
  OrderDetail.JSON_PROPERTY_FAIL_MSG,
  OrderDetail.JSON_PROPERTY_CREATED_AT,
  OrderDetail.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:54:52.457772+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class OrderDetail {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Long id;

  public static final String JSON_PROPERTY_SHOP_ID = "shopId";
  @jakarta.annotation.Nonnull
  private Long shopId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nonnull
  private Long userId;

  public static final String JSON_PROPERTY_CAPTURE = "capture";
  @jakarta.annotation.Nonnull
  private String capture;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private BigDecimal amount;

  public static final String JSON_PROPERTY_FX_TIME = "fxTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime fxTime;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private Integer status;

  public static final String JSON_PROPERTY_FAIL_MSG = "failMsg";
  @jakarta.annotation.Nullable
  private String failMsg;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public OrderDetail() {
  }

  public OrderDetail id(@jakarta.annotation.Nonnull Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Long id) {
    this.id = id;
  }

  public OrderDetail shopId(@jakarta.annotation.Nonnull Long shopId) {
    
    this.shopId = shopId;
    return this;
  }

  /**
   * Get shopId
   * @return shopId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getShopId() {
    return shopId;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopId(@jakarta.annotation.Nonnull Long shopId) {
    this.shopId = shopId;
  }

  public OrderDetail userId(@jakarta.annotation.Nonnull Long userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Long userId) {
    this.userId = userId;
  }

  public OrderDetail capture(@jakarta.annotation.Nonnull String capture) {
    
    this.capture = capture;
    return this;
  }

  /**
   * Get capture
   * @return capture
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CAPTURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCapture() {
    return capture;
  }


  @JsonProperty(JSON_PROPERTY_CAPTURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCapture(@jakarta.annotation.Nonnull String capture) {
    this.capture = capture;
  }

  public OrderDetail amount(@jakarta.annotation.Nonnull BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull BigDecimal amount) {
    this.amount = amount;
  }

  public OrderDetail fxTime(@jakarta.annotation.Nullable OffsetDateTime fxTime) {
    
    this.fxTime = fxTime;
    return this;
  }

  /**
   * Get fxTime
   * @return fxTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FX_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFxTime() {
    return fxTime;
  }


  @JsonProperty(JSON_PROPERTY_FX_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFxTime(@jakarta.annotation.Nullable OffsetDateTime fxTime) {
    this.fxTime = fxTime;
  }

  public OrderDetail status(@jakarta.annotation.Nonnull Integer status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull Integer status) {
    this.status = status;
  }

  public OrderDetail failMsg(@jakarta.annotation.Nullable String failMsg) {
    
    this.failMsg = failMsg;
    return this;
  }

  /**
   * Get failMsg
   * @return failMsg
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAIL_MSG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFailMsg() {
    return failMsg;
  }


  @JsonProperty(JSON_PROPERTY_FAIL_MSG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailMsg(@jakarta.annotation.Nullable String failMsg) {
    this.failMsg = failMsg;
  }

  public OrderDetail createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public OrderDetail updatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDetail orderDetail = (OrderDetail) o;
    return Objects.equals(this.id, orderDetail.id) &&
        Objects.equals(this.shopId, orderDetail.shopId) &&
        Objects.equals(this.userId, orderDetail.userId) &&
        Objects.equals(this.capture, orderDetail.capture) &&
        Objects.equals(this.amount, orderDetail.amount) &&
        Objects.equals(this.fxTime, orderDetail.fxTime) &&
        Objects.equals(this.status, orderDetail.status) &&
        Objects.equals(this.failMsg, orderDetail.failMsg) &&
        Objects.equals(this.createdAt, orderDetail.createdAt) &&
        Objects.equals(this.updatedAt, orderDetail.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shopId, userId, capture, amount, fxTime, status, failMsg, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    capture: ").append(toIndentedString(capture)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    fxTime: ").append(toIndentedString(fxTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    failMsg: ").append(toIndentedString(failMsg)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

