/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.account.dal.generator;


import com.iqexception.fxhelper.account.dal.generator.tables.FxAccount;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FX_ACCOUNT_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_account_idx_created_at"), FxAccount.FX_ACCOUNT, new OrderField[] { FxAccount.FX_ACCOUNT.CREATED_AT }, false);
    public static final Index FX_ACCOUNT_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_account_idx_updated_at"), FxAccount.FX_ACCOUNT, new OrderField[] { FxAccount.FX_ACCOUNT.UPDATED_AT }, false);
}
