/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.account.dal.generator;


import com.iqexception.fxhelper.account.dal.generator.tables.FxAccount;
import com.iqexception.fxhelper.account.dal.generator.tables.records.FxAccountRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxAccountRecord> CONSTRAINT_1 = Internal.createUniqueKey(FxAccount.FX_ACCOUNT, DSL.name("CONSTRAINT_1"), new TableField[] { FxAccount.FX_ACCOUNT.ACCOUNT_ID }, true);
    public static final UniqueKey<FxAccountRecord> CONSTRAINT_1B = Internal.createUniqueKey(FxAccount.FX_ACCOUNT, DSL.name("CONSTRAINT_1B"), new TableField[] { FxAccount.FX_ACCOUNT.USER_ID }, true);
}
