/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.account.dal.generator;


import com.iqexception.fxhelper.account.dal.generator.tables.FxAccount;


/**
 * Convenience access to all tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>fx.fx_account</code>.
     */
    public static final FxAccount FX_ACCOUNT = FxAccount.FX_ACCOUNT;
}
