/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator;


import com.iqexception.fxhelper.shop.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.shop.dal.generator.tables.FxShop;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FX_SERIAL_IDX_NO_CREATED_AT = Internal.createIndex(DSL.name("fx_serial_idx_no_created_at"), FxSerialNo.FX_SERIAL_NO, new OrderField[] { FxSerialNo.FX_SERIAL_NO.CREATED_AT }, false);
    public static final Index FX_SERIAL_IDX_NO_SHOP_I__26_SERIAL_NO = Internal.createIndex(DSL.name("fx_serial_idx_no_shop_i_&_serial_no"), FxSerialNo.FX_SERIAL_NO, new OrderField[] { FxSerialNo.FX_SERIAL_NO.SHOP_ID, FxSerialNo.FX_SERIAL_NO.SERIAL_NO }, true);
    public static final Index FX_SHOP_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_shop_idx_created_at"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.CREATED_AT }, false);
    public static final Index FX_SHOP_IDX_OWNER_USER_ID = Internal.createIndex(DSL.name("fx_shop_idx_owner_user_id"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.OWNER_USER_ID }, false);
    public static final Index FX_SHOP_IDX_PHONE = Internal.createIndex(DSL.name("fx_shop_idx_phone"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.PHONE }, false);
    public static final Index FX_SHOP_IDX_SHOP_NAME = Internal.createIndex(DSL.name("fx_shop_idx_shop_name"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.SHOP_NAME }, false);
    public static final Index FX_SHOP_IDX_SHOP_NAME__26_ADDRESS = Internal.createIndex(DSL.name("fx_shop_idx_shop_name_&_address"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.SHOP_NAME, FxShop.FX_SHOP.ADDRESS }, true);
    public static final Index FX_SHOP_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_shop_idx_updated_at"), FxShop.FX_SHOP, new OrderField[] { FxShop.FX_SHOP.UPDATED_AT }, false);
}
