/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator;


import com.iqexception.fxhelper.shop.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.shop.dal.generator.tables.FxShop;
import com.iqexception.fxhelper.shop.dal.generator.tables.records.FxSerialNoRecord;
import com.iqexception.fxhelper.shop.dal.generator.tables.records.FxShopRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxSerialNoRecord> CONSTRAINT_6 = Internal.createUniqueKey(FxSerialNo.FX_SERIAL_NO, DSL.name("CONSTRAINT_6"), new TableField[] { FxSerialNo.FX_SERIAL_NO.ID }, true);
    public static final UniqueKey<FxShopRecord> CONSTRAINT_E = Internal.createUniqueKey(FxShop.FX_SHOP, DSL.name("CONSTRAINT_E"), new TableField[] { FxShop.FX_SHOP.SHOP_ID }, true);
}
