/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator;


import com.iqexception.fxhelper.shop.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.shop.dal.generator.tables.FxShop;


/**
 * Convenience access to all tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>fx.fx_serial_no</code>.
     */
    public static final FxSerialNo FX_SERIAL_NO = FxSerialNo.FX_SERIAL_NO;

    /**
     * The table <code>fx.fx_shop</code>.
     */
    public static final FxShop FX_SHOP = FxShop.FX_SHOP;
}
