/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.user.dal.generator.tables.daos;


import com.iqexception.fxhelper.user.dal.generator.tables.FxUser;
import com.iqexception.fxhelper.user.dal.generator.tables.records.FxUserRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxUserDao extends DAOImpl<FxUserRecord, com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser, Long> {

    /**
     * Create a new FxUserDao without any configuration
     */
    public FxUserDao() {
        super(FxUser.FX_USER, com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser.class);
    }

    /**
     * Create a new FxUserDao with an attached configuration
     */
    @Autowired
    public FxUserDao(Configuration configuration) {
        super(FxUser.FX_USER, com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>USER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxUser.FX_USER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByUserId(Long... values) {
        return fetch(FxUser.FX_USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>USER_ID = value</code>
     */
    public com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser fetchOneByUserId(Long value) {
        return fetchOne(FxUser.FX_USER.USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>USER_ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchOptionalByUserId(Long value) {
        return fetchOptional(FxUser.FX_USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>NICK_NAME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfNickName(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.NICK_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>NICK_NAME IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByNickName(String... values) {
        return fetch(FxUser.FX_USER.NICK_NAME, values);
    }

    /**
     * Fetch records that have <code>AVATAR BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfAvatar(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.AVATAR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>AVATAR IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByAvatar(String... values) {
        return fetch(FxUser.FX_USER.AVATAR, values);
    }

    /**
     * Fetch records that have <code>OPEN_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfOpenId(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.OPEN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>OPEN_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByOpenId(String... values) {
        return fetch(FxUser.FX_USER.OPEN_ID, values);
    }

    /**
     * Fetch a unique record that has <code>OPEN_ID = value</code>
     */
    public com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser fetchOneByOpenId(String value) {
        return fetchOne(FxUser.FX_USER.OPEN_ID, value);
    }

    /**
     * Fetch a unique record that has <code>OPEN_ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchOptionalByOpenId(String value) {
        return fetchOptional(FxUser.FX_USER.OPEN_ID, value);
    }

    /**
     * Fetch records that have <code>UNION_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfUnionId(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.UNION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UNION_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByUnionId(String... values) {
        return fetch(FxUser.FX_USER.UNION_ID, values);
    }

    /**
     * Fetch records that have <code>SESSION_KEY BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfSessionKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.SESSION_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SESSION_KEY IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchBySessionKey(String... values) {
        return fetch(FxUser.FX_USER.SESSION_KEY, values);
    }

    /**
     * Fetch records that have <code>PHONE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PHONE IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByPhone(String... values) {
        return fetch(FxUser.FX_USER.PHONE, values);
    }

    /**
     * Fetch records that have <code>PAY_SECRET BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfPaySecret(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxUser.FX_USER.PAY_SECRET, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PAY_SECRET IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByPaySecret(String... values) {
        return fetch(FxUser.FX_USER.PAY_SECRET, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxUser.FX_USER.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxUser.FX_USER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxUser.FX_USER.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(FxUser.FX_USER.UPDATED_AT, values);
    }
}
