/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator;


import com.iqexception.fxhelper.order.dal.generator.tables.FxOrder;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fx extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx</code>
     */
    public static final Fx FX = new Fx();

    /**
     * The table <code>fx.fx_order</code>.
     */
    public final FxOrder FX_ORDER = FxOrder.FX_ORDER;

    /**
     * No further instances allowed
     */
    private Fx() {
        super("fx", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FxOrder.FX_ORDER
        );
    }
}
