/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator;


import com.iqexception.fxhelper.order.dal.generator.tables.FxOrder;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FX_ORDER_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_order_idx_created_at"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.CREATED_AT }, false);
    public static final Index FX_ORDER_IDX_FX_TIME = Internal.createIndex(DSL.name("fx_order_idx_fx_time"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.FX_TIME }, false);
    public static final Index FX_ORDER_IDX_SHOP_ID = Internal.createIndex(DSL.name("fx_order_idx_shop_id"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.SHOP_ID }, false);
    public static final Index FX_ORDER_IDX_SHOP_ID__26_SERIAL_NO = Internal.createIndex(DSL.name("fx_order_idx_shop_id_&_serial_no"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.SHOP_ID, FxOrder.FX_ORDER.SERIAL_NO }, true);
    public static final Index FX_ORDER_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_order_idx_updated_at"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.UPDATED_AT }, false);
    public static final Index FX_ORDER_IDX_USER_ID = Internal.createIndex(DSL.name("fx_order_idx_user_id"), FxOrder.FX_ORDER, new OrderField[] { FxOrder.FX_ORDER.USER_ID }, false);
}
