/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator;


import com.iqexception.fxhelper.order.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.order.dal.generator.tables.records.FxOrderRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxOrderRecord> CONSTRAINT_D = Internal.createUniqueKey(FxOrder.FX_ORDER, DSL.name("CONSTRAINT_D"), new TableField[] { FxOrder.FX_ORDER.ID }, true);
}
