/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator.tables.records;


import com.iqexception.fxhelper.shop.dal.generator.tables.FxSerialNo;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxSerialNoRecord extends UpdatableRecordImpl<FxSerialNoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_serial_no.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_serial_no.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_serial_no.SHOP_ID</code>.
     */
    public void setShopId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_serial_no.SHOP_ID</code>.
     */
    public Long getShopId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fx.fx_serial_no.SERIAL_NO</code>.
     */
    public void setSerialNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_serial_no.SERIAL_NO</code>.
     */
    public String getSerialNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_serial_no.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_serial_no.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxSerialNoRecord
     */
    public FxSerialNoRecord() {
        super(FxSerialNo.FX_SERIAL_NO);
    }

    /**
     * Create a detached, initialised FxSerialNoRecord
     */
    public FxSerialNoRecord(Long id, Long shopId, String serialNo, LocalDateTime createdAt) {
        super(FxSerialNo.FX_SERIAL_NO);

        setId(id);
        setShopId(shopId);
        setSerialNo(serialNo);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxSerialNoRecord
     */
    public FxSerialNoRecord(com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo value) {
        super(FxSerialNo.FX_SERIAL_NO);

        if (value != null) {
            setId(value.getId());
            setShopId(value.getShopId());
            setSerialNo(value.getSerialNo());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
