/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator.tables.records;


import com.iqexception.fxhelper.shop.dal.generator.tables.FxShop;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxShopRecord extends UpdatableRecordImpl<FxShopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_shop.SHOP_ID</code>.
     */
    public void setShopId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_shop.SHOP_ID</code>.
     */
    public Long getShopId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_shop.OWNER_USER_ID</code>.
     */
    public void setOwnerUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_shop.OWNER_USER_ID</code>.
     */
    public Long getOwnerUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fx.fx_shop.SHOP_NAME</code>.
     */
    public void setShopName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_shop.SHOP_NAME</code>.
     */
    public String getShopName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_shop.LOGO</code>.
     */
    public void setLogo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_shop.LOGO</code>.
     */
    public String getLogo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fx.fx_shop.INTRO</code>.
     */
    public void setIntro(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_shop.INTRO</code>.
     */
    public String getIntro() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fx.fx_shop.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_shop.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fx.fx_shop.STATUS</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fx.fx_shop.STATUS</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fx.fx_shop.PHONE</code>.
     */
    public void setPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fx.fx_shop.PHONE</code>.
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fx.fx_shop.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>fx.fx_shop.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>fx.fx_shop.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fx.fx_shop.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxShopRecord
     */
    public FxShopRecord() {
        super(FxShop.FX_SHOP);
    }

    /**
     * Create a detached, initialised FxShopRecord
     */
    public FxShopRecord(Long shopId, Long ownerUserId, String shopName, String logo, String intro, String address, Integer status, String phone, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxShop.FX_SHOP);

        setShopId(shopId);
        setOwnerUserId(ownerUserId);
        setShopName(shopName);
        setLogo(logo);
        setIntro(intro);
        setAddress(address);
        setStatus(status);
        setPhone(phone);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxShopRecord
     */
    public FxShopRecord(com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxShop value) {
        super(FxShop.FX_SHOP);

        if (value != null) {
            setShopId(value.getShopId());
            setOwnerUserId(value.getOwnerUserId());
            setShopName(value.getShopName());
            setLogo(value.getLogo());
            setIntro(value.getIntro());
            setAddress(value.getAddress());
            setStatus(value.getStatus());
            setPhone(value.getPhone());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
