/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.user.dal.generator.tables;


import com.iqexception.fxhelper.user.dal.generator.Fx;
import com.iqexception.fxhelper.user.dal.generator.Indexes;
import com.iqexception.fxhelper.user.dal.generator.Keys;
import com.iqexception.fxhelper.user.dal.generator.tables.records.FxUserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxUser extends TableImpl<FxUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_user</code>
     */
    public static final FxUser FX_USER = new FxUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxUserRecord> getRecordType() {
        return FxUserRecord.class;
    }

    /**
     * The column <code>fx.fx_user.USER_ID</code>.
     */
    public final TableField<FxUserRecord, Long> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_user.NICK_NAME</code>.
     */
    public final TableField<FxUserRecord, String> NICK_NAME = createField(DSL.name("NICK_NAME"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>fx.fx_user.AVATAR</code>.
     */
    public final TableField<FxUserRecord, String> AVATAR = createField(DSL.name("AVATAR"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_user.OPEN_ID</code>.
     */
    public final TableField<FxUserRecord, String> OPEN_ID = createField(DSL.name("OPEN_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_user.UNION_ID</code>.
     */
    public final TableField<FxUserRecord, String> UNION_ID = createField(DSL.name("UNION_ID"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>fx.fx_user.SESSION_KEY</code>.
     */
    public final TableField<FxUserRecord, String> SESSION_KEY = createField(DSL.name("SESSION_KEY"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>fx.fx_user.PHONE</code>.
     */
    public final TableField<FxUserRecord, String> PHONE = createField(DSL.name("PHONE"), SQLDataType.CHAR(11), this, "");

    /**
     * The column <code>fx.fx_user.PAY_SECRET</code>.
     */
    public final TableField<FxUserRecord, String> PAY_SECRET = createField(DSL.name("PAY_SECRET"), SQLDataType.CHAR(64), this, "");

    /**
     * The column <code>fx.fx_user.CREATED_AT</code>.
     */
    public final TableField<FxUserRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_user.UPDATED_AT</code>.
     */
    public final TableField<FxUserRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxUser(Name alias, Table<FxUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxUser(Name alias, Table<FxUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_user</code> table reference
     */
    public FxUser(String alias) {
        this(DSL.name(alias), FX_USER);
    }

    /**
     * Create an aliased <code>fx.fx_user</code> table reference
     */
    public FxUser(Name alias) {
        this(alias, FX_USER);
    }

    /**
     * Create a <code>fx.fx_user</code> table reference
     */
    public FxUser() {
        this(DSL.name("fx_user"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_USER_IDX_CREATED_AT, Indexes.FX_USER_IDX_NICK_NAME, Indexes.FX_USER_IDX_OPEN_ID, Indexes.FX_USER_IDX_PHONE, Indexes.FX_USER_IDX_SESSION_KEY, Indexes.FX_USER_IDX_UNION_ID, Indexes.FX_USER_IDX_UPDATED_AT);
    }

    @Override
    public Identity<FxUserRecord, Long> getIdentity() {
        return (Identity<FxUserRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxUserRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_E;
    }

    @Override
    public List<UniqueKey<FxUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_E5);
    }

    @Override
    public FxUser as(String alias) {
        return new FxUser(DSL.name(alias), this);
    }

    @Override
    public FxUser as(Name alias) {
        return new FxUser(alias, this);
    }

    @Override
    public FxUser as(Table<?> alias) {
        return new FxUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxUser rename(String name) {
        return new FxUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxUser rename(Name name) {
        return new FxUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxUser rename(Table<?> name) {
        return new FxUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxUser where(Condition condition) {
        return new FxUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
