/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator.tables;


import com.iqexception.fxhelper.shop.dal.generator.Fx;
import com.iqexception.fxhelper.shop.dal.generator.Indexes;
import com.iqexception.fxhelper.shop.dal.generator.Keys;
import com.iqexception.fxhelper.shop.dal.generator.tables.records.FxShopRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxShop extends TableImpl<FxShopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_shop</code>
     */
    public static final FxShop FX_SHOP = new FxShop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxShopRecord> getRecordType() {
        return FxShopRecord.class;
    }

    /**
     * The column <code>fx.fx_shop.SHOP_ID</code>.
     */
    public final TableField<FxShopRecord, Long> SHOP_ID = createField(DSL.name("SHOP_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_shop.OWNER_USER_ID</code>.
     */
    public final TableField<FxShopRecord, Long> OWNER_USER_ID = createField(DSL.name("OWNER_USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>fx.fx_shop.SHOP_NAME</code>.
     */
    public final TableField<FxShopRecord, String> SHOP_NAME = createField(DSL.name("SHOP_NAME"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>fx.fx_shop.LOGO</code>.
     */
    public final TableField<FxShopRecord, String> LOGO = createField(DSL.name("LOGO"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_shop.INTRO</code>.
     */
    public final TableField<FxShopRecord, String> INTRO = createField(DSL.name("INTRO"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_shop.ADDRESS</code>.
     */
    public final TableField<FxShopRecord, String> ADDRESS = createField(DSL.name("ADDRESS"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_shop.STATUS</code>.
     */
    public final TableField<FxShopRecord, Integer> STATUS = createField(DSL.name("STATUS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_shop.PHONE</code>.
     */
    public final TableField<FxShopRecord, String> PHONE = createField(DSL.name("PHONE"), SQLDataType.CHAR(11).nullable(false), this, "");

    /**
     * The column <code>fx.fx_shop.CREATED_AT</code>.
     */
    public final TableField<FxShopRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_shop.UPDATED_AT</code>.
     */
    public final TableField<FxShopRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxShop(Name alias, Table<FxShopRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxShop(Name alias, Table<FxShopRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_shop</code> table reference
     */
    public FxShop(String alias) {
        this(DSL.name(alias), FX_SHOP);
    }

    /**
     * Create an aliased <code>fx.fx_shop</code> table reference
     */
    public FxShop(Name alias) {
        this(alias, FX_SHOP);
    }

    /**
     * Create a <code>fx.fx_shop</code> table reference
     */
    public FxShop() {
        this(DSL.name("fx_shop"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_SHOP_IDX_CREATED_AT, Indexes.FX_SHOP_IDX_OWNER_USER_ID, Indexes.FX_SHOP_IDX_PHONE, Indexes.FX_SHOP_IDX_SHOP_NAME, Indexes.FX_SHOP_IDX_SHOP_NAME__26_ADDRESS, Indexes.FX_SHOP_IDX_UPDATED_AT);
    }

    @Override
    public Identity<FxShopRecord, Long> getIdentity() {
        return (Identity<FxShopRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxShopRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_E;
    }

    @Override
    public FxShop as(String alias) {
        return new FxShop(DSL.name(alias), this);
    }

    @Override
    public FxShop as(Name alias) {
        return new FxShop(alias, this);
    }

    @Override
    public FxShop as(Table<?> alias) {
        return new FxShop(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxShop rename(String name) {
        return new FxShop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxShop rename(Name name) {
        return new FxShop(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxShop rename(Table<?> name) {
        return new FxShop(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxShop where(Condition condition) {
        return new FxShop(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxShop where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxShop where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxShop where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxShop where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxShop where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxShop where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxShop where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxShop whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxShop whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
