/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long shopId;
    private Long userId;
    private String capture;
    private BigDecimal amount;
    private LocalDateTime fxTime;
    private Integer status;
    private String serialNo;
    private String failMsg;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FxOrder() {}

    public FxOrder(FxOrder value) {
        this.id = value.id;
        this.shopId = value.shopId;
        this.userId = value.userId;
        this.capture = value.capture;
        this.amount = value.amount;
        this.fxTime = value.fxTime;
        this.status = value.status;
        this.serialNo = value.serialNo;
        this.failMsg = value.failMsg;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FxOrder(
        Long id,
        Long shopId,
        Long userId,
        String capture,
        BigDecimal amount,
        LocalDateTime fxTime,
        Integer status,
        String serialNo,
        String failMsg,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.shopId = shopId;
        this.userId = userId;
        this.capture = capture;
        this.amount = amount;
        this.fxTime = fxTime;
        this.status = status;
        this.serialNo = serialNo;
        this.failMsg = failMsg;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>fx.fx_order.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>fx.fx_order.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>fx.fx_order.SHOP_ID</code>.
     */
    public Long getShopId() {
        return this.shopId;
    }

    /**
     * Setter for <code>fx.fx_order.SHOP_ID</code>.
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * Getter for <code>fx.fx_order.USER_ID</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fx.fx_order.USER_ID</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fx.fx_order.CAPTURE</code>.
     */
    public String getCapture() {
        return this.capture;
    }

    /**
     * Setter for <code>fx.fx_order.CAPTURE</code>.
     */
    public void setCapture(String capture) {
        this.capture = capture;
    }

    /**
     * Getter for <code>fx.fx_order.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>fx.fx_order.AMOUNT</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>fx.fx_order.FX_TIME</code>.
     */
    public LocalDateTime getFxTime() {
        return this.fxTime;
    }

    /**
     * Setter for <code>fx.fx_order.FX_TIME</code>.
     */
    public void setFxTime(LocalDateTime fxTime) {
        this.fxTime = fxTime;
    }

    /**
     * Getter for <code>fx.fx_order.STATUS</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>fx.fx_order.STATUS</code>.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>fx.fx_order.SERIAL_NO</code>.
     */
    public String getSerialNo() {
        return this.serialNo;
    }

    /**
     * Setter for <code>fx.fx_order.SERIAL_NO</code>.
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * Getter for <code>fx.fx_order.FAIL_MSG</code>.
     */
    public String getFailMsg() {
        return this.failMsg;
    }

    /**
     * Setter for <code>fx.fx_order.FAIL_MSG</code>.
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg;
    }

    /**
     * Getter for <code>fx.fx_order.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>fx.fx_order.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>fx.fx_order.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>fx.fx_order.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FxOrder other = (FxOrder) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!this.shopId.equals(other.shopId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.capture == null) {
            if (other.capture != null)
                return false;
        }
        else if (!this.capture.equals(other.capture))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.fxTime == null) {
            if (other.fxTime != null)
                return false;
        }
        else if (!this.fxTime.equals(other.fxTime))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.serialNo == null) {
            if (other.serialNo != null)
                return false;
        }
        else if (!this.serialNo.equals(other.serialNo))
            return false;
        if (this.failMsg == null) {
            if (other.failMsg != null)
                return false;
        }
        else if (!this.failMsg.equals(other.failMsg))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.capture == null) ? 0 : this.capture.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.fxTime == null) ? 0 : this.fxTime.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.serialNo == null) ? 0 : this.serialNo.hashCode());
        result = prime * result + ((this.failMsg == null) ? 0 : this.failMsg.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FxOrder (");

        sb.append(id);
        sb.append(", ").append(shopId);
        sb.append(", ").append(userId);
        sb.append(", ").append(capture);
        sb.append(", ").append(amount);
        sb.append(", ").append(fxTime);
        sb.append(", ").append(status);
        sb.append(", ").append(serialNo);
        sb.append(", ").append(failMsg);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
