/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator.tables.daos;


import com.iqexception.fxhelper.order.dal.generator.tables.FxOrder;
import com.iqexception.fxhelper.order.dal.generator.tables.records.FxOrderRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxOrderDao extends DAOImpl<FxOrderRecord, com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder, Long> {

    /**
     * Create a new FxOrderDao without any configuration
     */
    public FxOrderDao() {
        super(FxOrder.FX_ORDER, com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder.class);
    }

    /**
     * Create a new FxOrderDao with an attached configuration
     */
    @Autowired
    public FxOrderDao(Configuration configuration) {
        super(FxOrder.FX_ORDER, com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchById(Long... values) {
        return fetch(FxOrder.FX_ORDER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder fetchOneById(Long value) {
        return fetchOne(FxOrder.FX_ORDER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchOptionalById(Long value) {
        return fetchOptional(FxOrder.FX_ORDER.ID, value);
    }

    /**
     * Fetch records that have <code>SHOP_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfShopId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.SHOP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SHOP_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByShopId(Long... values) {
        return fetch(FxOrder.FX_ORDER.SHOP_ID, values);
    }

    /**
     * Fetch records that have <code>USER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByUserId(Long... values) {
        return fetch(FxOrder.FX_ORDER.USER_ID, values);
    }

    /**
     * Fetch records that have <code>CAPTURE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfCapture(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.CAPTURE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CAPTURE IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByCapture(String... values) {
        return fetch(FxOrder.FX_ORDER.CAPTURE, values);
    }

    /**
     * Fetch records that have <code>AMOUNT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>AMOUNT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByAmount(BigDecimal... values) {
        return fetch(FxOrder.FX_ORDER.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>FX_TIME BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfFxTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.FX_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>FX_TIME IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByFxTime(LocalDateTime... values) {
        return fetch(FxOrder.FX_ORDER.FX_TIME, values);
    }

    /**
     * Fetch records that have <code>STATUS BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByStatus(Integer... values) {
        return fetch(FxOrder.FX_ORDER.STATUS, values);
    }

    /**
     * Fetch records that have <code>SERIAL_NO BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfSerialNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.SERIAL_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SERIAL_NO IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchBySerialNo(String... values) {
        return fetch(FxOrder.FX_ORDER.SERIAL_NO, values);
    }

    /**
     * Fetch records that have <code>FAIL_MSG BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfFailMsg(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.FAIL_MSG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>FAIL_MSG IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByFailMsg(String... values) {
        return fetch(FxOrder.FX_ORDER.FAIL_MSG, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxOrder.FX_ORDER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxOrder.FX_ORDER.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(FxOrder.FX_ORDER.UPDATED_AT, values);
    }
}
