/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.account.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InternalTransferRequest
 */
@JsonPropertyOrder({
  InternalTransferRequest.JSON_PROPERTY_SECRET_KEY,
  InternalTransferRequest.JSON_PROPERTY_TO_ACCOUNT_ID,
  InternalTransferRequest.JSON_PROPERTY_FROM_ACCOUNT_ID,
  InternalTransferRequest.JSON_PROPERTY_AMOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:54:00.716180+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class InternalTransferRequest {
  public static final String JSON_PROPERTY_SECRET_KEY = "secretKey";
  @jakarta.annotation.Nonnull
  private String secretKey;

  public static final String JSON_PROPERTY_TO_ACCOUNT_ID = "toAccountId";
  @jakarta.annotation.Nonnull
  private Long toAccountId;

  public static final String JSON_PROPERTY_FROM_ACCOUNT_ID = "fromAccountId";
  @jakarta.annotation.Nonnull
  private Long fromAccountId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private BigDecimal amount;

  public InternalTransferRequest() {
  }

  public InternalTransferRequest secretKey(@jakarta.annotation.Nonnull String secretKey) {
    
    this.secretKey = secretKey;
    return this;
  }

  /**
   * Get secretKey
   * @return secretKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SECRET_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSecretKey() {
    return secretKey;
  }


  @JsonProperty(JSON_PROPERTY_SECRET_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecretKey(@jakarta.annotation.Nonnull String secretKey) {
    this.secretKey = secretKey;
  }

  public InternalTransferRequest toAccountId(@jakarta.annotation.Nonnull Long toAccountId) {
    
    this.toAccountId = toAccountId;
    return this;
  }

  /**
   * Get toAccountId
   * @return toAccountId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getToAccountId() {
    return toAccountId;
  }


  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToAccountId(@jakarta.annotation.Nonnull Long toAccountId) {
    this.toAccountId = toAccountId;
  }

  public InternalTransferRequest fromAccountId(@jakarta.annotation.Nonnull Long fromAccountId) {
    
    this.fromAccountId = fromAccountId;
    return this;
  }

  /**
   * Get fromAccountId
   * @return fromAccountId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getFromAccountId() {
    return fromAccountId;
  }


  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromAccountId(@jakarta.annotation.Nonnull Long fromAccountId) {
    this.fromAccountId = fromAccountId;
  }

  public InternalTransferRequest amount(@jakarta.annotation.Nonnull BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull BigDecimal amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalTransferRequest internalTransferRequest = (InternalTransferRequest) o;
    return Objects.equals(this.secretKey, internalTransferRequest.secretKey) &&
        Objects.equals(this.toAccountId, internalTransferRequest.toAccountId) &&
        Objects.equals(this.fromAccountId, internalTransferRequest.fromAccountId) &&
        Objects.equals(this.amount, internalTransferRequest.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secretKey, toAccountId, fromAccountId, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalTransferRequest {\n");
    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
    sb.append("    toAccountId: ").append(toIndentedString(toAccountId)).append("\n");
    sb.append("    fromAccountId: ").append(toIndentedString(fromAccountId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

