/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator.tables.records;


import com.iqexception.fxhelper.order.dal.generator.tables.FxOrder;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxOrderRecord extends UpdatableRecordImpl<FxOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_order.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_order.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_order.SHOP_ID</code>.
     */
    public void setShopId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_order.SHOP_ID</code>.
     */
    public Long getShopId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fx.fx_order.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_order.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fx.fx_order.CAPTURE</code>.
     */
    public void setCapture(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_order.CAPTURE</code>.
     */
    public String getCapture() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fx.fx_order.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_order.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>fx.fx_order.FX_TIME</code>.
     */
    public void setFxTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_order.FX_TIME</code>.
     */
    public LocalDateTime getFxTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>fx.fx_order.STATUS</code>.
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fx.fx_order.STATUS</code>.
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fx.fx_order.SERIAL_NO</code>.
     */
    public void setSerialNo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fx.fx_order.SERIAL_NO</code>.
     */
    public String getSerialNo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fx.fx_order.FAIL_MSG</code>.
     */
    public void setFailMsg(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fx.fx_order.FAIL_MSG</code>.
     */
    public String getFailMsg() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fx.fx_order.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fx.fx_order.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>fx.fx_order.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>fx.fx_order.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxOrderRecord
     */
    public FxOrderRecord() {
        super(FxOrder.FX_ORDER);
    }

    /**
     * Create a detached, initialised FxOrderRecord
     */
    public FxOrderRecord(Long id, Long shopId, Long userId, String capture, BigDecimal amount, LocalDateTime fxTime, Integer status, String serialNo, String failMsg, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxOrder.FX_ORDER);

        setId(id);
        setShopId(shopId);
        setUserId(userId);
        setCapture(capture);
        setAmount(amount);
        setFxTime(fxTime);
        setStatus(status);
        setSerialNo(serialNo);
        setFailMsg(failMsg);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxOrderRecord
     */
    public FxOrderRecord(com.iqexception.fxhelper.order.dal.generator.tables.pojos.FxOrder value) {
        super(FxOrder.FX_ORDER);

        if (value != null) {
            setId(value.getId());
            setShopId(value.getShopId());
            setUserId(value.getUserId());
            setCapture(value.getCapture());
            setAmount(value.getAmount());
            setFxTime(value.getFxTime());
            setStatus(value.getStatus());
            setSerialNo(value.getSerialNo());
            setFailMsg(value.getFailMsg());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
