/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.user.dal.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private String nickName;
    private String avatar;
    private String openId;
    private String unionId;
    private String sessionKey;
    private String phone;
    private String paySecret;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FxUser() {}

    public FxUser(FxUser value) {
        this.userId = value.userId;
        this.nickName = value.nickName;
        this.avatar = value.avatar;
        this.openId = value.openId;
        this.unionId = value.unionId;
        this.sessionKey = value.sessionKey;
        this.phone = value.phone;
        this.paySecret = value.paySecret;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FxUser(
        Long userId,
        String nickName,
        String avatar,
        String openId,
        String unionId,
        String sessionKey,
        String phone,
        String paySecret,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.userId = userId;
        this.nickName = nickName;
        this.avatar = avatar;
        this.openId = openId;
        this.unionId = unionId;
        this.sessionKey = sessionKey;
        this.phone = phone;
        this.paySecret = paySecret;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>fx.fx_user.USER_ID</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fx.fx_user.USER_ID</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fx.fx_user.NICK_NAME</code>.
     */
    public String getNickName() {
        return this.nickName;
    }

    /**
     * Setter for <code>fx.fx_user.NICK_NAME</code>.
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * Getter for <code>fx.fx_user.AVATAR</code>.
     */
    public String getAvatar() {
        return this.avatar;
    }

    /**
     * Setter for <code>fx.fx_user.AVATAR</code>.
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * Getter for <code>fx.fx_user.OPEN_ID</code>.
     */
    public String getOpenId() {
        return this.openId;
    }

    /**
     * Setter for <code>fx.fx_user.OPEN_ID</code>.
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * Getter for <code>fx.fx_user.UNION_ID</code>.
     */
    public String getUnionId() {
        return this.unionId;
    }

    /**
     * Setter for <code>fx.fx_user.UNION_ID</code>.
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * Getter for <code>fx.fx_user.SESSION_KEY</code>.
     */
    public String getSessionKey() {
        return this.sessionKey;
    }

    /**
     * Setter for <code>fx.fx_user.SESSION_KEY</code>.
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /**
     * Getter for <code>fx.fx_user.PHONE</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>fx.fx_user.PHONE</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>fx.fx_user.PAY_SECRET</code>.
     */
    public String getPaySecret() {
        return this.paySecret;
    }

    /**
     * Setter for <code>fx.fx_user.PAY_SECRET</code>.
     */
    public void setPaySecret(String paySecret) {
        this.paySecret = paySecret;
    }

    /**
     * Getter for <code>fx.fx_user.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>fx.fx_user.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>fx.fx_user.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>fx.fx_user.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FxUser other = (FxUser) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.nickName == null) {
            if (other.nickName != null)
                return false;
        }
        else if (!this.nickName.equals(other.nickName))
            return false;
        if (this.avatar == null) {
            if (other.avatar != null)
                return false;
        }
        else if (!this.avatar.equals(other.avatar))
            return false;
        if (this.openId == null) {
            if (other.openId != null)
                return false;
        }
        else if (!this.openId.equals(other.openId))
            return false;
        if (this.unionId == null) {
            if (other.unionId != null)
                return false;
        }
        else if (!this.unionId.equals(other.unionId))
            return false;
        if (this.sessionKey == null) {
            if (other.sessionKey != null)
                return false;
        }
        else if (!this.sessionKey.equals(other.sessionKey))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.paySecret == null) {
            if (other.paySecret != null)
                return false;
        }
        else if (!this.paySecret.equals(other.paySecret))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.nickName == null) ? 0 : this.nickName.hashCode());
        result = prime * result + ((this.avatar == null) ? 0 : this.avatar.hashCode());
        result = prime * result + ((this.openId == null) ? 0 : this.openId.hashCode());
        result = prime * result + ((this.unionId == null) ? 0 : this.unionId.hashCode());
        result = prime * result + ((this.sessionKey == null) ? 0 : this.sessionKey.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.paySecret == null) ? 0 : this.paySecret.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FxUser (");

        sb.append(userId);
        sb.append(", ").append(nickName);
        sb.append(", ").append(avatar);
        sb.append(", ").append(openId);
        sb.append(", ").append(unionId);
        sb.append(", ").append(sessionKey);
        sb.append(", ").append(phone);
        sb.append(", ").append(paySecret);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
