/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetPublicShopInfoResult
 */
@JsonPropertyOrder({
  GetPublicShopInfoResult.JSON_PROPERTY_SHOP_NAME,
  GetPublicShopInfoResult.JSON_PROPERTY_LOGO,
  GetPublicShopInfoResult.JSON_PROPERTY_INTRO,
  GetPublicShopInfoResult.JSON_PROPERTY_ADDRESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class GetPublicShopInfoResult {
  public static final String JSON_PROPERTY_SHOP_NAME = "shopName";
  @jakarta.annotation.Nonnull
  private String shopName;

  public static final String JSON_PROPERTY_LOGO = "logo";
  @jakarta.annotation.Nonnull
  private String logo;

  public static final String JSON_PROPERTY_INTRO = "intro";
  @jakarta.annotation.Nonnull
  private String intro;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public GetPublicShopInfoResult() {
  }

  public GetPublicShopInfoResult shopName(@jakarta.annotation.Nonnull String shopName) {
    
    this.shopName = shopName;
    return this;
  }

  /**
   * Get shopName
   * @return shopName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getShopName() {
    return shopName;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopName(@jakarta.annotation.Nonnull String shopName) {
    this.shopName = shopName;
  }

  public GetPublicShopInfoResult logo(@jakarta.annotation.Nonnull String logo) {
    
    this.logo = logo;
    return this;
  }

  /**
   * Get logo
   * @return logo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLogo() {
    return logo;
  }


  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogo(@jakarta.annotation.Nonnull String logo) {
    this.logo = logo;
  }

  public GetPublicShopInfoResult intro(@jakarta.annotation.Nonnull String intro) {
    
    this.intro = intro;
    return this;
  }

  /**
   * Get intro
   * @return intro
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTRO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIntro() {
    return intro;
  }


  @JsonProperty(JSON_PROPERTY_INTRO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIntro(@jakarta.annotation.Nonnull String intro) {
    this.intro = intro;
  }

  public GetPublicShopInfoResult address(@jakarta.annotation.Nonnull String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPublicShopInfoResult getPublicShopInfoResult = (GetPublicShopInfoResult) o;
    return Objects.equals(this.shopName, getPublicShopInfoResult.shopName) &&
        Objects.equals(this.logo, getPublicShopInfoResult.logo) &&
        Objects.equals(this.intro, getPublicShopInfoResult.intro) &&
        Objects.equals(this.address, getPublicShopInfoResult.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopName, logo, intro, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPublicShopInfoResult {\n");
    sb.append("    shopName: ").append(toIndentedString(shopName)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    intro: ").append(toIndentedString(intro)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

