/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetQrCodesResult
 */
@JsonPropertyOrder({
  GetQrCodesResult.JSON_PROPERTY_QR_CODES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class GetQrCodesResult {
  public static final String JSON_PROPERTY_QR_CODES = "qrCodes";
  @jakarta.annotation.Nullable
  private List<String> qrCodes = new ArrayList<>();

  public GetQrCodesResult() {
  }

  public GetQrCodesResult qrCodes(@jakarta.annotation.Nullable List<String> qrCodes) {
    
    this.qrCodes = qrCodes;
    return this;
  }

  public GetQrCodesResult addQrCodesItem(String qrCodesItem) {
    if (this.qrCodes == null) {
      this.qrCodes = new ArrayList<>();
    }
    this.qrCodes.add(qrCodesItem);
    return this;
  }

  /**
   * Get qrCodes
   * @return qrCodes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QR_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getQrCodes() {
    return qrCodes;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCodes(@jakarta.annotation.Nullable List<String> qrCodes) {
    this.qrCodes = qrCodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetQrCodesResult getQrCodesResult = (GetQrCodesResult) o;
    return Objects.equals(this.qrCodes, getQrCodesResult.qrCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qrCodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetQrCodesResult {\n");
    sb.append("    qrCodes: ").append(toIndentedString(qrCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

