/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.iqexception.fxhelper.client.resttemplate.shop.model.ShopDetail;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetShopListResult
 */
@JsonPropertyOrder({
  GetShopListResult.JSON_PROPERTY_SHOP_LIST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class GetShopListResult {
  public static final String JSON_PROPERTY_SHOP_LIST = "shopList";
  @jakarta.annotation.Nullable
  private List<ShopDetail> shopList = new ArrayList<>();

  public GetShopListResult() {
  }

  public GetShopListResult shopList(@jakarta.annotation.Nullable List<ShopDetail> shopList) {
    
    this.shopList = shopList;
    return this;
  }

  public GetShopListResult addShopListItem(ShopDetail shopListItem) {
    if (this.shopList == null) {
      this.shopList = new ArrayList<>();
    }
    this.shopList.add(shopListItem);
    return this;
  }

  /**
   * Get shopList
   * @return shopList
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOP_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ShopDetail> getShopList() {
    return shopList;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopList(@jakarta.annotation.Nullable List<ShopDetail> shopList) {
    this.shopList = shopList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetShopListResult getShopListResult = (GetShopListResult) o;
    return Objects.equals(this.shopList, getShopListResult.shopList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetShopListResult {\n");
    sb.append("    shopList: ").append(toIndentedString(shopList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

