/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetShopDetailInfoResult
 */
@JsonPropertyOrder({
  GetShopDetailInfoResult.JSON_PROPERTY_SHOP_ID,
  GetShopDetailInfoResult.JSON_PROPERTY_OWNER_USER_ID,
  GetShopDetailInfoResult.JSON_PROPERTY_SHOP_NAME,
  GetShopDetailInfoResult.JSON_PROPERTY_LOGO,
  GetShopDetailInfoResult.JSON_PROPERTY_INTRO,
  GetShopDetailInfoResult.JSON_PROPERTY_ADDRESS,
  GetShopDetailInfoResult.JSON_PROPERTY_PHONE,
  GetShopDetailInfoResult.JSON_PROPERTY_STATUS,
  GetShopDetailInfoResult.JSON_PROPERTY_CREATED_AT,
  GetShopDetailInfoResult.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class GetShopDetailInfoResult {
  public static final String JSON_PROPERTY_SHOP_ID = "shopId";
  @jakarta.annotation.Nonnull
  private Long shopId;

  public static final String JSON_PROPERTY_OWNER_USER_ID = "ownerUserId";
  @jakarta.annotation.Nonnull
  private Long ownerUserId;

  public static final String JSON_PROPERTY_SHOP_NAME = "shopName";
  @jakarta.annotation.Nonnull
  private String shopName;

  public static final String JSON_PROPERTY_LOGO = "logo";
  @jakarta.annotation.Nonnull
  private String logo;

  public static final String JSON_PROPERTY_INTRO = "intro";
  @jakarta.annotation.Nonnull
  private String intro;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @jakarta.annotation.Nonnull
  private String phone;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private Integer status;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public GetShopDetailInfoResult() {
  }

  public GetShopDetailInfoResult shopId(@jakarta.annotation.Nonnull Long shopId) {
    
    this.shopId = shopId;
    return this;
  }

  /**
   * Get shopId
   * @return shopId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getShopId() {
    return shopId;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopId(@jakarta.annotation.Nonnull Long shopId) {
    this.shopId = shopId;
  }

  public GetShopDetailInfoResult ownerUserId(@jakarta.annotation.Nonnull Long ownerUserId) {
    
    this.ownerUserId = ownerUserId;
    return this;
  }

  /**
   * Get ownerUserId
   * @return ownerUserId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OWNER_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOwnerUserId() {
    return ownerUserId;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwnerUserId(@jakarta.annotation.Nonnull Long ownerUserId) {
    this.ownerUserId = ownerUserId;
  }

  public GetShopDetailInfoResult shopName(@jakarta.annotation.Nonnull String shopName) {
    
    this.shopName = shopName;
    return this;
  }

  /**
   * Get shopName
   * @return shopName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getShopName() {
    return shopName;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopName(@jakarta.annotation.Nonnull String shopName) {
    this.shopName = shopName;
  }

  public GetShopDetailInfoResult logo(@jakarta.annotation.Nonnull String logo) {
    
    this.logo = logo;
    return this;
  }

  /**
   * Get logo
   * @return logo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLogo() {
    return logo;
  }


  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogo(@jakarta.annotation.Nonnull String logo) {
    this.logo = logo;
  }

  public GetShopDetailInfoResult intro(@jakarta.annotation.Nonnull String intro) {
    
    this.intro = intro;
    return this;
  }

  /**
   * Get intro
   * @return intro
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTRO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIntro() {
    return intro;
  }


  @JsonProperty(JSON_PROPERTY_INTRO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIntro(@jakarta.annotation.Nonnull String intro) {
    this.intro = intro;
  }

  public GetShopDetailInfoResult address(@jakarta.annotation.Nonnull String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }

  public GetShopDetailInfoResult phone(@jakarta.annotation.Nonnull String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhone(@jakarta.annotation.Nonnull String phone) {
    this.phone = phone;
  }

  public GetShopDetailInfoResult status(@jakarta.annotation.Nonnull Integer status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull Integer status) {
    this.status = status;
  }

  public GetShopDetailInfoResult createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public GetShopDetailInfoResult updatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@jakarta.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetShopDetailInfoResult getShopDetailInfoResult = (GetShopDetailInfoResult) o;
    return Objects.equals(this.shopId, getShopDetailInfoResult.shopId) &&
        Objects.equals(this.ownerUserId, getShopDetailInfoResult.ownerUserId) &&
        Objects.equals(this.shopName, getShopDetailInfoResult.shopName) &&
        Objects.equals(this.logo, getShopDetailInfoResult.logo) &&
        Objects.equals(this.intro, getShopDetailInfoResult.intro) &&
        Objects.equals(this.address, getShopDetailInfoResult.address) &&
        Objects.equals(this.phone, getShopDetailInfoResult.phone) &&
        Objects.equals(this.status, getShopDetailInfoResult.status) &&
        Objects.equals(this.createdAt, getShopDetailInfoResult.createdAt) &&
        Objects.equals(this.updatedAt, getShopDetailInfoResult.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopId, ownerUserId, shopName, logo, intro, address, phone, status, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetShopDetailInfoResult {\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("    ownerUserId: ").append(toIndentedString(ownerUserId)).append("\n");
    sb.append("    shopName: ").append(toIndentedString(shopName)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    intro: ").append(toIndentedString(intro)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

