/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InternalGetShopListRequest
 */
@JsonPropertyOrder({
  InternalGetShopListRequest.JSON_PROPERTY_SHOP_IDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class InternalGetShopListRequest {
  public static final String JSON_PROPERTY_SHOP_IDS = "shopIds";
  @jakarta.annotation.Nonnull
  private List<Long> shopIds = new ArrayList<>();

  public InternalGetShopListRequest() {
  }

  public InternalGetShopListRequest shopIds(@jakarta.annotation.Nonnull List<Long> shopIds) {
    
    this.shopIds = shopIds;
    return this;
  }

  public InternalGetShopListRequest addShopIdsItem(Long shopIdsItem) {
    if (this.shopIds == null) {
      this.shopIds = new ArrayList<>();
    }
    this.shopIds.add(shopIdsItem);
    return this;
  }

  /**
   * Get shopIds
   * @return shopIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Long> getShopIds() {
    return shopIds;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopIds(@jakarta.annotation.Nonnull List<Long> shopIds) {
    this.shopIds = shopIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalGetShopListRequest internalGetShopListRequest = (InternalGetShopListRequest) o;
    return Objects.equals(this.shopIds, internalGetShopListRequest.shopIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalGetShopListRequest {\n");
    sb.append("    shopIds: ").append(toIndentedString(shopIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

