/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ShopCreateParam
 */
@JsonPropertyOrder({
  ShopCreateParam.JSON_PROPERTY_ADDRESS,
  ShopCreateParam.JSON_PROPERTY_NAME,
  ShopCreateParam.JSON_PROPERTY_LOGO,
  ShopCreateParam.JSON_PROPERTY_PHONE,
  ShopCreateParam.JSON_PROPERTY_INTRO,
  ShopCreateParam.JSON_PROPERTY_PAY_SECRET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class ShopCreateParam {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_LOGO = "logo";
  @jakarta.annotation.Nonnull
  private String logo;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @jakarta.annotation.Nonnull
  private String phone;

  public static final String JSON_PROPERTY_INTRO = "intro";
  @jakarta.annotation.Nonnull
  private String intro;

  public static final String JSON_PROPERTY_PAY_SECRET = "paySecret";
  @jakarta.annotation.Nonnull
  private String paySecret;

  public ShopCreateParam() {
  }

  public ShopCreateParam address(@jakarta.annotation.Nonnull String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }

  public ShopCreateParam name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public ShopCreateParam logo(@jakarta.annotation.Nonnull String logo) {
    
    this.logo = logo;
    return this;
  }

  /**
   * Get logo
   * @return logo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLogo() {
    return logo;
  }


  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogo(@jakarta.annotation.Nonnull String logo) {
    this.logo = logo;
  }

  public ShopCreateParam phone(@jakarta.annotation.Nonnull String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhone(@jakarta.annotation.Nonnull String phone) {
    this.phone = phone;
  }

  public ShopCreateParam intro(@jakarta.annotation.Nonnull String intro) {
    
    this.intro = intro;
    return this;
  }

  /**
   * Get intro
   * @return intro
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INTRO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIntro() {
    return intro;
  }


  @JsonProperty(JSON_PROPERTY_INTRO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIntro(@jakarta.annotation.Nonnull String intro) {
    this.intro = intro;
  }

  public ShopCreateParam paySecret(@jakarta.annotation.Nonnull String paySecret) {
    
    this.paySecret = paySecret;
    return this;
  }

  /**
   * Get paySecret
   * @return paySecret
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAY_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPaySecret() {
    return paySecret;
  }


  @JsonProperty(JSON_PROPERTY_PAY_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaySecret(@jakarta.annotation.Nonnull String paySecret) {
    this.paySecret = paySecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopCreateParam shopCreateParam = (ShopCreateParam) o;
    return Objects.equals(this.address, shopCreateParam.address) &&
        Objects.equals(this.name, shopCreateParam.name) &&
        Objects.equals(this.logo, shopCreateParam.logo) &&
        Objects.equals(this.phone, shopCreateParam.phone) &&
        Objects.equals(this.intro, shopCreateParam.intro) &&
        Objects.equals(this.paySecret, shopCreateParam.paySecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, name, logo, phone, intro, paySecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopCreateParam {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    intro: ").append(toIndentedString(intro)).append("\n");
    sb.append("    paySecret: ").append(toIndentedString(paySecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

