/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.shop.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SwitchParam
 */
@JsonPropertyOrder({
  SwitchParam.JSON_PROPERTY_SHOP_ID,
  SwitchParam.JSON_PROPERTY_SWITCH_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-17T02:48:31.789852+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class SwitchParam {
  public static final String JSON_PROPERTY_SHOP_ID = "shopId";
  @jakarta.annotation.Nonnull
  private Long shopId;

  public static final String JSON_PROPERTY_SWITCH_VALUE = "switchValue";
  @jakarta.annotation.Nonnull
  private Integer switchValue;

  public SwitchParam() {
  }

  public SwitchParam shopId(@jakarta.annotation.Nonnull Long shopId) {
    
    this.shopId = shopId;
    return this;
  }

  /**
   * Get shopId
   * @return shopId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getShopId() {
    return shopId;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShopId(@jakarta.annotation.Nonnull Long shopId) {
    this.shopId = shopId;
  }

  public SwitchParam switchValue(@jakarta.annotation.Nonnull Integer switchValue) {
    
    this.switchValue = switchValue;
    return this;
  }

  /**
   * Get switchValue
   * minimum: 0
   * maximum: 1
   * @return switchValue
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SWITCH_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSwitchValue() {
    return switchValue;
  }


  @JsonProperty(JSON_PROPERTY_SWITCH_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSwitchValue(@jakarta.annotation.Nonnull Integer switchValue) {
    this.switchValue = switchValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SwitchParam switchParam = (SwitchParam) o;
    return Objects.equals(this.shopId, switchParam.shopId) &&
        Objects.equals(this.switchValue, switchParam.switchValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopId, switchValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SwitchParam {\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("    switchValue: ").append(toIndentedString(switchValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

