/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.pay.dal.generator.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxPayInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer fromChannel;
    private String fromAccount;
    private String fromTrxId;
    private Integer toChannel;
    private String toAccount;
    private String toTrxId;
    private String bizId;
    private BigDecimal amount;
    private String status;
    private JSON payAcctInfo;
    private JSON recvAcctInfo;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FxPayInfo() {}

    public FxPayInfo(FxPayInfo value) {
        this.id = value.id;
        this.fromChannel = value.fromChannel;
        this.fromAccount = value.fromAccount;
        this.fromTrxId = value.fromTrxId;
        this.toChannel = value.toChannel;
        this.toAccount = value.toAccount;
        this.toTrxId = value.toTrxId;
        this.bizId = value.bizId;
        this.amount = value.amount;
        this.status = value.status;
        this.payAcctInfo = value.payAcctInfo;
        this.recvAcctInfo = value.recvAcctInfo;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FxPayInfo(
        Long id,
        Integer fromChannel,
        String fromAccount,
        String fromTrxId,
        Integer toChannel,
        String toAccount,
        String toTrxId,
        String bizId,
        BigDecimal amount,
        String status,
        JSON payAcctInfo,
        JSON recvAcctInfo,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.fromChannel = fromChannel;
        this.fromAccount = fromAccount;
        this.fromTrxId = fromTrxId;
        this.toChannel = toChannel;
        this.toAccount = toAccount;
        this.toTrxId = toTrxId;
        this.bizId = bizId;
        this.amount = amount;
        this.status = status;
        this.payAcctInfo = payAcctInfo;
        this.recvAcctInfo = recvAcctInfo;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>fx.fx_pay_info.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>fx.fx_pay_info.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>fx.fx_pay_info.FROM_CHANNEL</code>.
     */
    public Integer getFromChannel() {
        return this.fromChannel;
    }

    /**
     * Setter for <code>fx.fx_pay_info.FROM_CHANNEL</code>.
     */
    public void setFromChannel(Integer fromChannel) {
        this.fromChannel = fromChannel;
    }

    /**
     * Getter for <code>fx.fx_pay_info.FROM_ACCOUNT</code>.
     */
    public String getFromAccount() {
        return this.fromAccount;
    }

    /**
     * Setter for <code>fx.fx_pay_info.FROM_ACCOUNT</code>.
     */
    public void setFromAccount(String fromAccount) {
        this.fromAccount = fromAccount;
    }

    /**
     * Getter for <code>fx.fx_pay_info.FROM_TRX_ID</code>.
     */
    public String getFromTrxId() {
        return this.fromTrxId;
    }

    /**
     * Setter for <code>fx.fx_pay_info.FROM_TRX_ID</code>.
     */
    public void setFromTrxId(String fromTrxId) {
        this.fromTrxId = fromTrxId;
    }

    /**
     * Getter for <code>fx.fx_pay_info.TO_CHANNEL</code>.
     */
    public Integer getToChannel() {
        return this.toChannel;
    }

    /**
     * Setter for <code>fx.fx_pay_info.TO_CHANNEL</code>.
     */
    public void setToChannel(Integer toChannel) {
        this.toChannel = toChannel;
    }

    /**
     * Getter for <code>fx.fx_pay_info.TO_ACCOUNT</code>.
     */
    public String getToAccount() {
        return this.toAccount;
    }

    /**
     * Setter for <code>fx.fx_pay_info.TO_ACCOUNT</code>.
     */
    public void setToAccount(String toAccount) {
        this.toAccount = toAccount;
    }

    /**
     * Getter for <code>fx.fx_pay_info.TO_TRX_ID</code>.
     */
    public String getToTrxId() {
        return this.toTrxId;
    }

    /**
     * Setter for <code>fx.fx_pay_info.TO_TRX_ID</code>.
     */
    public void setToTrxId(String toTrxId) {
        this.toTrxId = toTrxId;
    }

    /**
     * Getter for <code>fx.fx_pay_info.BIZ_ID</code>.
     */
    public String getBizId() {
        return this.bizId;
    }

    /**
     * Setter for <code>fx.fx_pay_info.BIZ_ID</code>.
     */
    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    /**
     * Getter for <code>fx.fx_pay_info.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>fx.fx_pay_info.AMOUNT</code>.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Getter for <code>fx.fx_pay_info.STATUS</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>fx.fx_pay_info.STATUS</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>fx.fx_pay_info.PAY_ACCT_INFO</code>.
     */
    public JSON getPayAcctInfo() {
        return this.payAcctInfo;
    }

    /**
     * Setter for <code>fx.fx_pay_info.PAY_ACCT_INFO</code>.
     */
    public void setPayAcctInfo(JSON payAcctInfo) {
        this.payAcctInfo = payAcctInfo;
    }

    /**
     * Getter for <code>fx.fx_pay_info.RECV_ACCT_INFO</code>.
     */
    public JSON getRecvAcctInfo() {
        return this.recvAcctInfo;
    }

    /**
     * Setter for <code>fx.fx_pay_info.RECV_ACCT_INFO</code>.
     */
    public void setRecvAcctInfo(JSON recvAcctInfo) {
        this.recvAcctInfo = recvAcctInfo;
    }

    /**
     * Getter for <code>fx.fx_pay_info.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>fx.fx_pay_info.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>fx.fx_pay_info.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>fx.fx_pay_info.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FxPayInfo other = (FxPayInfo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fromChannel == null) {
            if (other.fromChannel != null)
                return false;
        }
        else if (!this.fromChannel.equals(other.fromChannel))
            return false;
        if (this.fromAccount == null) {
            if (other.fromAccount != null)
                return false;
        }
        else if (!this.fromAccount.equals(other.fromAccount))
            return false;
        if (this.fromTrxId == null) {
            if (other.fromTrxId != null)
                return false;
        }
        else if (!this.fromTrxId.equals(other.fromTrxId))
            return false;
        if (this.toChannel == null) {
            if (other.toChannel != null)
                return false;
        }
        else if (!this.toChannel.equals(other.toChannel))
            return false;
        if (this.toAccount == null) {
            if (other.toAccount != null)
                return false;
        }
        else if (!this.toAccount.equals(other.toAccount))
            return false;
        if (this.toTrxId == null) {
            if (other.toTrxId != null)
                return false;
        }
        else if (!this.toTrxId.equals(other.toTrxId))
            return false;
        if (this.bizId == null) {
            if (other.bizId != null)
                return false;
        }
        else if (!this.bizId.equals(other.bizId))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.payAcctInfo == null) {
            if (other.payAcctInfo != null)
                return false;
        }
        else if (!this.payAcctInfo.equals(other.payAcctInfo))
            return false;
        if (this.recvAcctInfo == null) {
            if (other.recvAcctInfo != null)
                return false;
        }
        else if (!this.recvAcctInfo.equals(other.recvAcctInfo))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fromChannel == null) ? 0 : this.fromChannel.hashCode());
        result = prime * result + ((this.fromAccount == null) ? 0 : this.fromAccount.hashCode());
        result = prime * result + ((this.fromTrxId == null) ? 0 : this.fromTrxId.hashCode());
        result = prime * result + ((this.toChannel == null) ? 0 : this.toChannel.hashCode());
        result = prime * result + ((this.toAccount == null) ? 0 : this.toAccount.hashCode());
        result = prime * result + ((this.toTrxId == null) ? 0 : this.toTrxId.hashCode());
        result = prime * result + ((this.bizId == null) ? 0 : this.bizId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.payAcctInfo == null) ? 0 : this.payAcctInfo.hashCode());
        result = prime * result + ((this.recvAcctInfo == null) ? 0 : this.recvAcctInfo.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FxPayInfo (");

        sb.append(id);
        sb.append(", ").append(fromChannel);
        sb.append(", ").append(fromAccount);
        sb.append(", ").append(fromTrxId);
        sb.append(", ").append(toChannel);
        sb.append(", ").append(toAccount);
        sb.append(", ").append(toTrxId);
        sb.append(", ").append(bizId);
        sb.append(", ").append(amount);
        sb.append(", ").append(status);
        sb.append(", ").append(payAcctInfo);
        sb.append(", ").append(recvAcctInfo);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
