/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.order.dal.generator.tables;


import com.iqexception.fxhelper.order.dal.generator.Fx;
import com.iqexception.fxhelper.order.dal.generator.Indexes;
import com.iqexception.fxhelper.order.dal.generator.Keys;
import com.iqexception.fxhelper.order.dal.generator.tables.records.FxOrderRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxOrder extends TableImpl<FxOrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_order</code>
     */
    public static final FxOrder FX_ORDER = new FxOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxOrderRecord> getRecordType() {
        return FxOrderRecord.class;
    }

    /**
     * The column <code>fx.fx_order.ID</code>.
     */
    public final TableField<FxOrderRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_order.SHOP_ID</code>.
     */
    public final TableField<FxOrderRecord, Long> SHOP_ID = createField(DSL.name("SHOP_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>fx.fx_order.USER_ID</code>.
     */
    public final TableField<FxOrderRecord, Long> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>fx.fx_order.CAPTURE</code>.
     */
    public final TableField<FxOrderRecord, String> CAPTURE = createField(DSL.name("CAPTURE"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_order.AMOUNT</code>.
     */
    public final TableField<FxOrderRecord, BigDecimal> AMOUNT = createField(DSL.name("AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>fx.fx_order.FX_TIME</code>.
     */
    public final TableField<FxOrderRecord, LocalDateTime> FX_TIME = createField(DSL.name("FX_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>fx.fx_order.STATUS</code>.
     */
    public final TableField<FxOrderRecord, Integer> STATUS = createField(DSL.name("STATUS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_order.SERIAL_NO</code>.
     */
    public final TableField<FxOrderRecord, String> SERIAL_NO = createField(DSL.name("SERIAL_NO"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>fx.fx_order.FAIL_MSG</code>.
     */
    public final TableField<FxOrderRecord, String> FAIL_MSG = createField(DSL.name("FAIL_MSG"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>fx.fx_order.CREATED_AT</code>.
     */
    public final TableField<FxOrderRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_order.UPDATED_AT</code>.
     */
    public final TableField<FxOrderRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxOrder(Name alias, Table<FxOrderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxOrder(Name alias, Table<FxOrderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_order</code> table reference
     */
    public FxOrder(String alias) {
        this(DSL.name(alias), FX_ORDER);
    }

    /**
     * Create an aliased <code>fx.fx_order</code> table reference
     */
    public FxOrder(Name alias) {
        this(alias, FX_ORDER);
    }

    /**
     * Create a <code>fx.fx_order</code> table reference
     */
    public FxOrder() {
        this(DSL.name("fx_order"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_ORDER_IDX_CREATED_AT, Indexes.FX_ORDER_IDX_FX_TIME, Indexes.FX_ORDER_IDX_SHOP_ID, Indexes.FX_ORDER_IDX_SHOP_ID__26_SERIAL_NO, Indexes.FX_ORDER_IDX_UPDATED_AT, Indexes.FX_ORDER_IDX_USER_ID);
    }

    @Override
    public Identity<FxOrderRecord, Long> getIdentity() {
        return (Identity<FxOrderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxOrderRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    public FxOrder as(String alias) {
        return new FxOrder(DSL.name(alias), this);
    }

    @Override
    public FxOrder as(Name alias) {
        return new FxOrder(alias, this);
    }

    @Override
    public FxOrder as(Table<?> alias) {
        return new FxOrder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxOrder rename(String name) {
        return new FxOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxOrder rename(Name name) {
        return new FxOrder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxOrder rename(Table<?> name) {
        return new FxOrder(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxOrder where(Condition condition) {
        return new FxOrder(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxOrder where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxOrder where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxOrder where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxOrder where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxOrder where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxOrder where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxOrder where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxOrder whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxOrder whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
