/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator.tables;


import com.iqexception.fxhelper.misc.dal.generator.Fx;
import com.iqexception.fxhelper.misc.dal.generator.Indexes;
import com.iqexception.fxhelper.misc.dal.generator.Keys;
import com.iqexception.fxhelper.misc.dal.generator.tables.records.FxWxMessageRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxWxMessage extends TableImpl<FxWxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_wx_message</code>
     */
    public static final FxWxMessage FX_WX_MESSAGE = new FxWxMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxWxMessageRecord> getRecordType() {
        return FxWxMessageRecord.class;
    }

    /**
     * The column <code>fx.fx_wx_message.ID</code>.
     */
    public final TableField<FxWxMessageRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_wx_message.OPEN_ID</code>.
     */
    public final TableField<FxWxMessageRecord, String> OPEN_ID = createField(DSL.name("OPEN_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_wx_message.TEMPLATE_ID</code>.
     */
    public final TableField<FxWxMessageRecord, String> TEMPLATE_ID = createField(DSL.name("TEMPLATE_ID"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>fx.fx_wx_message.PAGE</code>.
     */
    public final TableField<FxWxMessageRecord, String> PAGE = createField(DSL.name("PAGE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>fx.fx_wx_message.MSG_BODY</code>.
     */
    public final TableField<FxWxMessageRecord, String> MSG_BODY = createField(DSL.name("MSG_BODY"), SQLDataType.VARCHAR(2000).nullable(false), this, "");

    /**
     * The column <code>fx.fx_wx_message.STATUS</code>.
     */
    public final TableField<FxWxMessageRecord, Integer> STATUS = createField(DSL.name("STATUS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_wx_message.FAIL_MSG</code>.
     */
    public final TableField<FxWxMessageRecord, String> FAIL_MSG = createField(DSL.name("FAIL_MSG"), SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>fx.fx_wx_message.CREATED_AT</code>.
     */
    public final TableField<FxWxMessageRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_wx_message.UPDATED_AT</code>.
     */
    public final TableField<FxWxMessageRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxWxMessage(Name alias, Table<FxWxMessageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxWxMessage(Name alias, Table<FxWxMessageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_wx_message</code> table reference
     */
    public FxWxMessage(String alias) {
        this(DSL.name(alias), FX_WX_MESSAGE);
    }

    /**
     * Create an aliased <code>fx.fx_wx_message</code> table reference
     */
    public FxWxMessage(Name alias) {
        this(alias, FX_WX_MESSAGE);
    }

    /**
     * Create a <code>fx.fx_wx_message</code> table reference
     */
    public FxWxMessage() {
        this(DSL.name("fx_wx_message"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_MESSAGE_IDX_CREATED_AT, Indexes.FX_MESSAGE_IDX_OPEN_ID, Indexes.FX_MESSAGE_IDX_TEMPLATE_ID, Indexes.FX_MESSAGE_IDX_UPDATED_AT);
    }

    @Override
    public Identity<FxWxMessageRecord, Long> getIdentity() {
        return (Identity<FxWxMessageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxWxMessageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    public FxWxMessage as(String alias) {
        return new FxWxMessage(DSL.name(alias), this);
    }

    @Override
    public FxWxMessage as(Name alias) {
        return new FxWxMessage(alias, this);
    }

    @Override
    public FxWxMessage as(Table<?> alias) {
        return new FxWxMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxWxMessage rename(String name) {
        return new FxWxMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxWxMessage rename(Name name) {
        return new FxWxMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxWxMessage rename(Table<?> name) {
        return new FxWxMessage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxWxMessage where(Condition condition) {
        return new FxWxMessage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxWxMessage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxWxMessage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxWxMessage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxWxMessage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxWxMessage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxWxMessage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxWxMessage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxWxMessage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxWxMessage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
