/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.account.dal.generator.tables.daos;


import com.iqexception.fxhelper.account.dal.generator.tables.FxAccount;
import com.iqexception.fxhelper.account.dal.generator.tables.records.FxAccountRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxAccountDao extends DAOImpl<FxAccountRecord, com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount, Long> {

    /**
     * Create a new FxAccountDao without any configuration
     */
    public FxAccountDao() {
        super(FxAccount.FX_ACCOUNT, com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount.class);
    }

    /**
     * Create a new FxAccountDao with an attached configuration
     */
    @Autowired
    public FxAccountDao(Configuration configuration) {
        super(FxAccount.FX_ACCOUNT, com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount object) {
        return object.getAccountId();
    }

    /**
     * Fetch records that have <code>ACCOUNT_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchRangeOfAccountId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxAccount.FX_ACCOUNT.ACCOUNT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ACCOUNT_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchByAccountId(Long... values) {
        return fetch(FxAccount.FX_ACCOUNT.ACCOUNT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>ACCOUNT_ID = value</code>
     */
    public com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount fetchOneByAccountId(Long value) {
        return fetchOne(FxAccount.FX_ACCOUNT.ACCOUNT_ID, value);
    }

    /**
     * Fetch a unique record that has <code>ACCOUNT_ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchOptionalByAccountId(Long value) {
        return fetchOptional(FxAccount.FX_ACCOUNT.ACCOUNT_ID, value);
    }

    /**
     * Fetch records that have <code>USER_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxAccount.FX_ACCOUNT.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchByUserId(Long... values) {
        return fetch(FxAccount.FX_ACCOUNT.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>USER_ID = value</code>
     */
    public com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount fetchOneByUserId(Long value) {
        return fetchOne(FxAccount.FX_ACCOUNT.USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>USER_ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchOptionalByUserId(Long value) {
        return fetchOptional(FxAccount.FX_ACCOUNT.USER_ID, value);
    }

    /**
     * Fetch records that have <code>BALANCE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchRangeOfBalance(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(FxAccount.FX_ACCOUNT.BALANCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>BALANCE IN (values)</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchByBalance(BigDecimal... values) {
        return fetch(FxAccount.FX_ACCOUNT.BALANCE, values);
    }

    /**
     * Fetch records that have <code>STATUS BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxAccount.FX_ACCOUNT.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchByStatus(Integer... values) {
        return fetch(FxAccount.FX_ACCOUNT.STATUS, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxAccount.FX_ACCOUNT.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxAccount.FX_ACCOUNT.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxAccount.FX_ACCOUNT.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.account.dal.generator.tables.pojos.FxAccount> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(FxAccount.FX_ACCOUNT.UPDATED_AT, values);
    }
}
