/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMessage;
import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMsgSubs;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fx extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx</code>
     */
    public static final Fx FX = new Fx();

    /**
     * The table <code>fx.fx_wx_message</code>.
     */
    public final FxWxMessage FX_WX_MESSAGE = FxWxMessage.FX_WX_MESSAGE;

    /**
     * The table <code>fx.fx_wx_msg_subs</code>.
     */
    public final FxWxMsgSubs FX_WX_MSG_SUBS = FxWxMsgSubs.FX_WX_MSG_SUBS;

    /**
     * No further instances allowed
     */
    private Fx() {
        super("fx", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FxWxMessage.FX_WX_MESSAGE,
            FxWxMsgSubs.FX_WX_MSG_SUBS
        );
    }
}
