/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMessage;
import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMsgSubs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FX_MESSAGE_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_message_idx_created_at"), FxWxMessage.FX_WX_MESSAGE, new OrderField[] { FxWxMessage.FX_WX_MESSAGE.CREATED_AT }, false);
    public static final Index FX_MESSAGE_IDX_OPEN_ID = Internal.createIndex(DSL.name("fx_message_idx_open_id"), FxWxMessage.FX_WX_MESSAGE, new OrderField[] { FxWxMessage.FX_WX_MESSAGE.OPEN_ID }, false);
    public static final Index FX_MESSAGE_IDX_TEMPLATE_ID = Internal.createIndex(DSL.name("fx_message_idx_template_id"), FxWxMessage.FX_WX_MESSAGE, new OrderField[] { FxWxMessage.FX_WX_MESSAGE.TEMPLATE_ID }, false);
    public static final Index FX_MESSAGE_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_message_idx_updated_at"), FxWxMessage.FX_WX_MESSAGE, new OrderField[] { FxWxMessage.FX_WX_MESSAGE.UPDATED_AT }, false);
    public static final Index FX_WX_MSG_SUBS_IDX_OPEN_ID__26_TEMPLATE_ID = Internal.createIndex(DSL.name("fx_wx_msg_subs_idx_open_id_&_template_id"), FxWxMsgSubs.FX_WX_MSG_SUBS, new OrderField[] { FxWxMsgSubs.FX_WX_MSG_SUBS.OPEN_ID, FxWxMsgSubs.FX_WX_MSG_SUBS.TEMPLATE_ID }, true);
}
