/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMessage;
import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMsgSubs;
import com.iqexception.fxhelper.misc.dal.generator.tables.records.FxWxMessageRecord;
import com.iqexception.fxhelper.misc.dal.generator.tables.records.FxWxMsgSubsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxWxMessageRecord> CONSTRAINT_B = Internal.createUniqueKey(FxWxMessage.FX_WX_MESSAGE, DSL.name("CONSTRAINT_B"), new TableField[] { FxWxMessage.FX_WX_MESSAGE.ID }, true);
    public static final UniqueKey<FxWxMsgSubsRecord> CONSTRAINT_1 = Internal.createUniqueKey(FxWxMsgSubs.FX_WX_MSG_SUBS, DSL.name("CONSTRAINT_1"), new TableField[] { FxWxMsgSubs.FX_WX_MSG_SUBS.ID }, true);
}
