/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator.tables.daos;


import com.iqexception.fxhelper.shop.dal.generator.tables.FxSerialNo;
import com.iqexception.fxhelper.shop.dal.generator.tables.records.FxSerialNoRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxSerialNoDao extends DAOImpl<FxSerialNoRecord, com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo, Long> {

    /**
     * Create a new FxSerialNoDao without any configuration
     */
    public FxSerialNoDao() {
        super(FxSerialNo.FX_SERIAL_NO, com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo.class);
    }

    /**
     * Create a new FxSerialNoDao with an attached configuration
     */
    @Autowired
    public FxSerialNoDao(Configuration configuration) {
        super(FxSerialNo.FX_SERIAL_NO, com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxSerialNo.FX_SERIAL_NO.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchById(Long... values) {
        return fetch(FxSerialNo.FX_SERIAL_NO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo fetchOneById(Long value) {
        return fetchOne(FxSerialNo.FX_SERIAL_NO.ID, value);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchOptionalById(Long value) {
        return fetchOptional(FxSerialNo.FX_SERIAL_NO.ID, value);
    }

    /**
     * Fetch records that have <code>SHOP_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchRangeOfShopId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxSerialNo.FX_SERIAL_NO.SHOP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SHOP_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchByShopId(Long... values) {
        return fetch(FxSerialNo.FX_SERIAL_NO.SHOP_ID, values);
    }

    /**
     * Fetch records that have <code>SERIAL_NO BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchRangeOfSerialNo(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxSerialNo.FX_SERIAL_NO.SERIAL_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SERIAL_NO IN (values)</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchBySerialNo(String... values) {
        return fetch(FxSerialNo.FX_SERIAL_NO.SERIAL_NO, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxSerialNo.FX_SERIAL_NO.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.shop.dal.generator.tables.pojos.FxSerialNo> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxSerialNo.FX_SERIAL_NO.CREATED_AT, values);
    }
}
