/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.misc.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.iqexception.fxhelper.client.resttemplate.misc.model.MobileRequestHead;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BaseRequest
 */
@JsonPropertyOrder({
  BaseRequest.JSON_PROPERTY_HEAD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:25:12.441376+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class BaseRequest {
  public static final String JSON_PROPERTY_HEAD = "head";
  @jakarta.annotation.Nullable
  private MobileRequestHead head;

  public BaseRequest() {
  }

  public BaseRequest head(@jakarta.annotation.Nullable MobileRequestHead head) {
    
    this.head = head;
    return this;
  }

  /**
   * Get head
   * @return head
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MobileRequestHead getHead() {
    return head;
  }


  @JsonProperty(JSON_PROPERTY_HEAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHead(@jakarta.annotation.Nullable MobileRequestHead head) {
    this.head = head;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseRequest baseRequest = (BaseRequest) o;
    return Objects.equals(this.head, baseRequest.head);
  }

  @Override
  public int hashCode() {
    return Objects.hash(head);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseRequest {\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

