/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.misc.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetUploadPolicyResult
 */
@JsonPropertyOrder({
  GetUploadPolicyResult.JSON_PROPERTY_POLICY,
  GetUploadPolicyResult.JSON_PROPERTY_SIGNATURE,
  GetUploadPolicyResult.JSON_PROPERTY_DIR,
  GetUploadPolicyResult.JSON_PROPERTY_HOST,
  GetUploadPolicyResult.JSON_PROPERTY_EXPIRE,
  GetUploadPolicyResult.JSON_PROPERTY_KEY,
  GetUploadPolicyResult.JSON_PROPERTY_ACCESSID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:25:12.441376+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class GetUploadPolicyResult {
  public static final String JSON_PROPERTY_POLICY = "policy";
  @jakarta.annotation.Nonnull
  private String policy;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @jakarta.annotation.Nonnull
  private String signature;

  public static final String JSON_PROPERTY_DIR = "dir";
  @jakarta.annotation.Nonnull
  private String dir;

  public static final String JSON_PROPERTY_HOST = "host";
  @jakarta.annotation.Nonnull
  private String host;

  public static final String JSON_PROPERTY_EXPIRE = "expire";
  @jakarta.annotation.Nonnull
  private String expire;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_ACCESSID = "accessid";
  @jakarta.annotation.Nonnull
  private String accessid;

  public GetUploadPolicyResult() {
  }

  public GetUploadPolicyResult policy(@jakarta.annotation.Nonnull String policy) {
    
    this.policy = policy;
    return this;
  }

  /**
   * Get policy
   * @return policy
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPolicy() {
    return policy;
  }


  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolicy(@jakarta.annotation.Nonnull String policy) {
    this.policy = policy;
  }

  public GetUploadPolicyResult signature(@jakarta.annotation.Nonnull String signature) {
    
    this.signature = signature;
    return this;
  }

  /**
   * Get signature
   * @return signature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(@jakarta.annotation.Nonnull String signature) {
    this.signature = signature;
  }

  public GetUploadPolicyResult dir(@jakarta.annotation.Nonnull String dir) {
    
    this.dir = dir;
    return this;
  }

  /**
   * Get dir
   * @return dir
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DIR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDir() {
    return dir;
  }


  @JsonProperty(JSON_PROPERTY_DIR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDir(@jakarta.annotation.Nonnull String dir) {
    this.dir = dir;
  }

  public GetUploadPolicyResult host(@jakarta.annotation.Nonnull String host) {
    
    this.host = host;
    return this;
  }

  /**
   * Get host
   * @return host
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HOST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHost() {
    return host;
  }


  @JsonProperty(JSON_PROPERTY_HOST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHost(@jakarta.annotation.Nonnull String host) {
    this.host = host;
  }

  public GetUploadPolicyResult expire(@jakarta.annotation.Nonnull String expire) {
    
    this.expire = expire;
    return this;
  }

  /**
   * Get expire
   * @return expire
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpire() {
    return expire;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpire(@jakarta.annotation.Nonnull String expire) {
    this.expire = expire;
  }

  public GetUploadPolicyResult key(@jakarta.annotation.Nonnull String key) {
    
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@jakarta.annotation.Nonnull String key) {
    this.key = key;
  }

  public GetUploadPolicyResult accessid(@jakarta.annotation.Nonnull String accessid) {
    
    this.accessid = accessid;
    return this;
  }

  /**
   * Get accessid
   * @return accessid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCESSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccessid() {
    return accessid;
  }


  @JsonProperty(JSON_PROPERTY_ACCESSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessid(@jakarta.annotation.Nonnull String accessid) {
    this.accessid = accessid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUploadPolicyResult getUploadPolicyResult = (GetUploadPolicyResult) o;
    return Objects.equals(this.policy, getUploadPolicyResult.policy) &&
        Objects.equals(this.signature, getUploadPolicyResult.signature) &&
        Objects.equals(this.dir, getUploadPolicyResult.dir) &&
        Objects.equals(this.host, getUploadPolicyResult.host) &&
        Objects.equals(this.expire, getUploadPolicyResult.expire) &&
        Objects.equals(this.key, getUploadPolicyResult.key) &&
        Objects.equals(this.accessid, getUploadPolicyResult.accessid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policy, signature, dir, host, expire, key, accessid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUploadPolicyResult {\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    dir: ").append(toIndentedString(dir)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    expire: ").append(toIndentedString(expire)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    accessid: ").append(toIndentedString(accessid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

