/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.pay.dal.generator.tables;


import com.iqexception.fxhelper.pay.dal.generator.Fx;
import com.iqexception.fxhelper.pay.dal.generator.Indexes;
import com.iqexception.fxhelper.pay.dal.generator.Keys;
import com.iqexception.fxhelper.pay.dal.generator.tables.records.FxPayInfoRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxPayInfo extends TableImpl<FxPayInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_pay_info</code>
     */
    public static final FxPayInfo FX_PAY_INFO = new FxPayInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxPayInfoRecord> getRecordType() {
        return FxPayInfoRecord.class;
    }

    /**
     * The column <code>fx.fx_pay_info.ID</code>.
     */
    public final TableField<FxPayInfoRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_pay_info.FROM_CHANNEL</code>.
     */
    public final TableField<FxPayInfoRecord, Integer> FROM_CHANNEL = createField(DSL.name("FROM_CHANNEL"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>fx.fx_pay_info.FROM_ACCOUNT</code>.
     */
    public final TableField<FxPayInfoRecord, String> FROM_ACCOUNT = createField(DSL.name("FROM_ACCOUNT"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>fx.fx_pay_info.FROM_TRX_ID</code>.
     */
    public final TableField<FxPayInfoRecord, String> FROM_TRX_ID = createField(DSL.name("FROM_TRX_ID"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>fx.fx_pay_info.TO_CHANNEL</code>.
     */
    public final TableField<FxPayInfoRecord, Integer> TO_CHANNEL = createField(DSL.name("TO_CHANNEL"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>fx.fx_pay_info.TO_ACCOUNT</code>.
     */
    public final TableField<FxPayInfoRecord, String> TO_ACCOUNT = createField(DSL.name("TO_ACCOUNT"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>fx.fx_pay_info.TO_TRX_ID</code>.
     */
    public final TableField<FxPayInfoRecord, String> TO_TRX_ID = createField(DSL.name("TO_TRX_ID"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>fx.fx_pay_info.BIZ_ID</code>.
     */
    public final TableField<FxPayInfoRecord, String> BIZ_ID = createField(DSL.name("BIZ_ID"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>fx.fx_pay_info.AMOUNT</code>.
     */
    public final TableField<FxPayInfoRecord, BigDecimal> AMOUNT = createField(DSL.name("AMOUNT"), SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>fx.fx_pay_info.STATUS</code>.
     */
    public final TableField<FxPayInfoRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>fx.fx_pay_info.PAY_ACCT_INFO</code>.
     */
    public final TableField<FxPayInfoRecord, JSON> PAY_ACCT_INFO = createField(DSL.name("PAY_ACCT_INFO"), SQLDataType.JSON, this, "");

    /**
     * The column <code>fx.fx_pay_info.RECV_ACCT_INFO</code>.
     */
    public final TableField<FxPayInfoRecord, JSON> RECV_ACCT_INFO = createField(DSL.name("RECV_ACCT_INFO"), SQLDataType.JSON, this, "");

    /**
     * The column <code>fx.fx_pay_info.CREATED_AT</code>.
     */
    public final TableField<FxPayInfoRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_pay_info.UPDATED_AT</code>.
     */
    public final TableField<FxPayInfoRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxPayInfo(Name alias, Table<FxPayInfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxPayInfo(Name alias, Table<FxPayInfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_pay_info</code> table reference
     */
    public FxPayInfo(String alias) {
        this(DSL.name(alias), FX_PAY_INFO);
    }

    /**
     * Create an aliased <code>fx.fx_pay_info</code> table reference
     */
    public FxPayInfo(Name alias) {
        this(alias, FX_PAY_INFO);
    }

    /**
     * Create a <code>fx.fx_pay_info</code> table reference
     */
    public FxPayInfo() {
        this(DSL.name("fx_pay_info"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_PAY_INFO_IDX_BIZ_ID, Indexes.FX_PAY_INFO_IDX_CREATED_AT, Indexes.FX_PAY_INFO_IDX_FROM_ACCOUNT, Indexes.FX_PAY_INFO_IDX_TO_ACCOUNT, Indexes.FX_PAY_INFO_IDX_UPDATED_AT);
    }

    @Override
    public Identity<FxPayInfoRecord, Long> getIdentity() {
        return (Identity<FxPayInfoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxPayInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public List<UniqueKey<FxPayInfoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_2C);
    }

    @Override
    public FxPayInfo as(String alias) {
        return new FxPayInfo(DSL.name(alias), this);
    }

    @Override
    public FxPayInfo as(Name alias) {
        return new FxPayInfo(alias, this);
    }

    @Override
    public FxPayInfo as(Table<?> alias) {
        return new FxPayInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxPayInfo rename(String name) {
        return new FxPayInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxPayInfo rename(Name name) {
        return new FxPayInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxPayInfo rename(Table<?> name) {
        return new FxPayInfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxPayInfo where(Condition condition) {
        return new FxPayInfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxPayInfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxPayInfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxPayInfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxPayInfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxPayInfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxPayInfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxPayInfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxPayInfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxPayInfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
