/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.user.dal.generator;


import com.iqexception.fxhelper.user.dal.generator.tables.FxUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FX_USER_IDX_CREATED_AT = Internal.createIndex(DSL.name("fx_user_idx_created_at"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.CREATED_AT }, false);
    public static final Index FX_USER_IDX_NICK_NAME = Internal.createIndex(DSL.name("fx_user_idx_nick_name"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.NICK_NAME }, false);
    public static final Index FX_USER_IDX_OPEN_ID = Internal.createIndex(DSL.name("fx_user_idx_open_id"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.OPEN_ID }, false);
    public static final Index FX_USER_IDX_PHONE = Internal.createIndex(DSL.name("fx_user_idx_phone"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.PHONE }, false);
    public static final Index FX_USER_IDX_SESSION_KEY = Internal.createIndex(DSL.name("fx_user_idx_session_key"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.SESSION_KEY }, false);
    public static final Index FX_USER_IDX_UNION_ID = Internal.createIndex(DSL.name("fx_user_idx_union_id"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.UNION_ID }, false);
    public static final Index FX_USER_IDX_UPDATED_AT = Internal.createIndex(DSL.name("fx_user_idx_updated_at"), FxUser.FX_USER, new OrderField[] { FxUser.FX_USER.UPDATED_AT }, false);
}
