/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.user.dal.generator;


import com.iqexception.fxhelper.user.dal.generator.tables.FxUser;
import com.iqexception.fxhelper.user.dal.generator.tables.records.FxUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxUserRecord> CONSTRAINT_E = Internal.createUniqueKey(FxUser.FX_USER, DSL.name("CONSTRAINT_E"), new TableField[] { FxUser.FX_USER.USER_ID }, true);
    public static final UniqueKey<FxUserRecord> CONSTRAINT_E5 = Internal.createUniqueKey(FxUser.FX_USER, DSL.name("CONSTRAINT_E5"), new TableField[] { FxUser.FX_USER.OPEN_ID }, true);
}
