/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MobileRequestHead
 */
@JsonPropertyOrder({
  MobileRequestHead.JSON_PROPERTY_PLATFORM,
  MobileRequestHead.JSON_PROPERTY_BRAND,
  MobileRequestHead.JSON_PROPERTY_MODEL,
  MobileRequestHead.JSON_PROPERTY_SYSTEM,
  MobileRequestHead.JSON_PROPERTY_DEVICE_ID,
  MobileRequestHead.JSON_PROPERTY_SIGN,
  MobileRequestHead.JSON_PROPERTY_IP,
  MobileRequestHead.JSON_PROPERTY_MAC,
  MobileRequestHead.JSON_PROPERTY_LATITUDE,
  MobileRequestHead.JSON_PROPERTY_LONGITUDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:23:05.087091+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class MobileRequestHead {
  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @jakarta.annotation.Nullable
  private String platform;

  public static final String JSON_PROPERTY_BRAND = "brand";
  @jakarta.annotation.Nullable
  private String brand;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private String model;

  public static final String JSON_PROPERTY_SYSTEM = "system";
  @jakarta.annotation.Nullable
  private String system;

  public static final String JSON_PROPERTY_DEVICE_ID = "deviceId";
  @jakarta.annotation.Nullable
  private String deviceId;

  public static final String JSON_PROPERTY_SIGN = "sign";
  @jakarta.annotation.Nullable
  private String sign;

  public static final String JSON_PROPERTY_IP = "ip";
  @jakarta.annotation.Nullable
  private String ip;

  public static final String JSON_PROPERTY_MAC = "mac";
  @jakarta.annotation.Nullable
  private String mac;

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  @jakarta.annotation.Nullable
  private String latitude;

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  @jakarta.annotation.Nullable
  private String longitude;

  public MobileRequestHead() {
  }

  public MobileRequestHead platform(@jakarta.annotation.Nullable String platform) {
    
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlatform() {
    return platform;
  }


  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(@jakarta.annotation.Nullable String platform) {
    this.platform = platform;
  }

  public MobileRequestHead brand(@jakarta.annotation.Nullable String brand) {
    
    this.brand = brand;
    return this;
  }

  /**
   * Get brand
   * @return brand
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BRAND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBrand() {
    return brand;
  }


  @JsonProperty(JSON_PROPERTY_BRAND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrand(@jakarta.annotation.Nullable String brand) {
    this.brand = brand;
  }

  public MobileRequestHead model(@jakarta.annotation.Nullable String model) {
    
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@jakarta.annotation.Nullable String model) {
    this.model = model;
  }

  public MobileRequestHead system(@jakarta.annotation.Nullable String system) {
    
    this.system = system;
    return this;
  }

  /**
   * Get system
   * @return system
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystem() {
    return system;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem(@jakarta.annotation.Nullable String system) {
    this.system = system;
  }

  public MobileRequestHead deviceId(@jakarta.annotation.Nullable String deviceId) {
    
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Get deviceId
   * @return deviceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeviceId() {
    return deviceId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceId(@jakarta.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
  }

  public MobileRequestHead sign(@jakarta.annotation.Nullable String sign) {
    
    this.sign = sign;
    return this;
  }

  /**
   * Get sign
   * @return sign
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSign() {
    return sign;
  }


  @JsonProperty(JSON_PROPERTY_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSign(@jakarta.annotation.Nullable String sign) {
    this.sign = sign;
  }

  public MobileRequestHead ip(@jakarta.annotation.Nullable String ip) {
    
    this.ip = ip;
    return this;
  }

  /**
   * Get ip
   * @return ip
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIp() {
    return ip;
  }


  @JsonProperty(JSON_PROPERTY_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIp(@jakarta.annotation.Nullable String ip) {
    this.ip = ip;
  }

  public MobileRequestHead mac(@jakarta.annotation.Nullable String mac) {
    
    this.mac = mac;
    return this;
  }

  /**
   * Get mac
   * @return mac
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMac() {
    return mac;
  }


  @JsonProperty(JSON_PROPERTY_MAC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMac(@jakarta.annotation.Nullable String mac) {
    this.mac = mac;
  }

  public MobileRequestHead latitude(@jakarta.annotation.Nullable String latitude) {
    
    this.latitude = latitude;
    return this;
  }

  /**
   * Get latitude
   * @return latitude
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatitude() {
    return latitude;
  }


  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatitude(@jakarta.annotation.Nullable String latitude) {
    this.latitude = latitude;
  }

  public MobileRequestHead longitude(@jakarta.annotation.Nullable String longitude) {
    
    this.longitude = longitude;
    return this;
  }

  /**
   * Get longitude
   * @return longitude
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLongitude() {
    return longitude;
  }


  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongitude(@jakarta.annotation.Nullable String longitude) {
    this.longitude = longitude;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MobileRequestHead mobileRequestHead = (MobileRequestHead) o;
    return Objects.equals(this.platform, mobileRequestHead.platform) &&
        Objects.equals(this.brand, mobileRequestHead.brand) &&
        Objects.equals(this.model, mobileRequestHead.model) &&
        Objects.equals(this.system, mobileRequestHead.system) &&
        Objects.equals(this.deviceId, mobileRequestHead.deviceId) &&
        Objects.equals(this.sign, mobileRequestHead.sign) &&
        Objects.equals(this.ip, mobileRequestHead.ip) &&
        Objects.equals(this.mac, mobileRequestHead.mac) &&
        Objects.equals(this.latitude, mobileRequestHead.latitude) &&
        Objects.equals(this.longitude, mobileRequestHead.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platform, brand, model, system, deviceId, sign, ip, mac, latitude, longitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MobileRequestHead {\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    sign: ").append(toIndentedString(sign)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    mac: ").append(toIndentedString(mac)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

