/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.iqexception.fxhelper.client.resttemplate.user.model.MobileRequestHead;
import com.iqexception.fxhelper.client.resttemplate.user.model.UserLoginParam;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RequestUserLoginParam
 */
@JsonPropertyOrder({
  RequestUserLoginParam.JSON_PROPERTY_HEAD,
  RequestUserLoginParam.JSON_PROPERTY_PARAM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:23:05.087091+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class RequestUserLoginParam {
  public static final String JSON_PROPERTY_HEAD = "head";
  @jakarta.annotation.Nonnull
  private MobileRequestHead head;

  public static final String JSON_PROPERTY_PARAM = "param";
  @jakarta.annotation.Nonnull
  private UserLoginParam param;

  public RequestUserLoginParam() {
  }

  public RequestUserLoginParam head(@jakarta.annotation.Nonnull MobileRequestHead head) {
    
    this.head = head;
    return this;
  }

  /**
   * Get head
   * @return head
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HEAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MobileRequestHead getHead() {
    return head;
  }


  @JsonProperty(JSON_PROPERTY_HEAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHead(@jakarta.annotation.Nonnull MobileRequestHead head) {
    this.head = head;
  }

  public RequestUserLoginParam param(@jakarta.annotation.Nonnull UserLoginParam param) {
    
    this.param = param;
    return this;
  }

  /**
   * Get param
   * @return param
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARAM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UserLoginParam getParam() {
    return param;
  }


  @JsonProperty(JSON_PROPERTY_PARAM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParam(@jakarta.annotation.Nonnull UserLoginParam param) {
    this.param = param;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestUserLoginParam requestUserLoginParam = (RequestUserLoginParam) o;
    return Objects.equals(this.head, requestUserLoginParam.head) &&
        Objects.equals(this.param, requestUserLoginParam.param);
  }

  @Override
  public int hashCode() {
    return Objects.hash(head, param);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestUserLoginParam {\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    param: ").append(toIndentedString(param)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

