/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.iqexception.fxhelper.client.resttemplate.user.model.InternalGetUserResult;
import com.iqexception.fxhelper.client.resttemplate.user.model.ResponseStatus;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResponseInternalGetUserResult
 */
@JsonPropertyOrder({
  ResponseInternalGetUserResult.JSON_PROPERTY_STATUS,
  ResponseInternalGetUserResult.JSON_PROPERTY_RESULT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:23:05.087091+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class ResponseInternalGetUserResult {
  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private ResponseStatus status;

  public static final String JSON_PROPERTY_RESULT = "result";
  @jakarta.annotation.Nullable
  private InternalGetUserResult result;

  public ResponseInternalGetUserResult() {
  }

  public ResponseInternalGetUserResult status(@jakarta.annotation.Nonnull ResponseStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull ResponseStatus status) {
    this.status = status;
  }

  public ResponseInternalGetUserResult result(@jakarta.annotation.Nullable InternalGetUserResult result) {
    
    this.result = result;
    return this;
  }

  /**
   * Get result
   * @return result
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InternalGetUserResult getResult() {
    return result;
  }


  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(@jakarta.annotation.Nullable InternalGetUserResult result) {
    this.result = result;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseInternalGetUserResult responseInternalGetUserResult = (ResponseInternalGetUserResult) o;
    return Objects.equals(this.status, responseInternalGetUserResult.status) &&
        Objects.equals(this.result, responseInternalGetUserResult.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseInternalGetUserResult {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

