/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.user.dal.generator.tables.records;


import com.iqexception.fxhelper.user.dal.generator.tables.FxUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxUserRecord extends UpdatableRecordImpl<FxUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fx.fx_user.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fx.fx_user.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fx.fx_user.NICK_NAME</code>.
     */
    public void setNickName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fx.fx_user.NICK_NAME</code>.
     */
    public String getNickName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fx.fx_user.AVATAR</code>.
     */
    public void setAvatar(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fx.fx_user.AVATAR</code>.
     */
    public String getAvatar() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fx.fx_user.OPEN_ID</code>.
     */
    public void setOpenId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fx.fx_user.OPEN_ID</code>.
     */
    public String getOpenId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fx.fx_user.UNION_ID</code>.
     */
    public void setUnionId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fx.fx_user.UNION_ID</code>.
     */
    public String getUnionId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fx.fx_user.SESSION_KEY</code>.
     */
    public void setSessionKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fx.fx_user.SESSION_KEY</code>.
     */
    public String getSessionKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fx.fx_user.PHONE</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fx.fx_user.PHONE</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fx.fx_user.PAY_SECRET</code>.
     */
    public void setPaySecret(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fx.fx_user.PAY_SECRET</code>.
     */
    public String getPaySecret() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fx.fx_user.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>fx.fx_user.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>fx.fx_user.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fx.fx_user.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxUserRecord
     */
    public FxUserRecord() {
        super(FxUser.FX_USER);
    }

    /**
     * Create a detached, initialised FxUserRecord
     */
    public FxUserRecord(Long userId, String nickName, String avatar, String openId, String unionId, String sessionKey, String phone, String paySecret, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FxUser.FX_USER);

        setUserId(userId);
        setNickName(nickName);
        setAvatar(avatar);
        setOpenId(openId);
        setUnionId(unionId);
        setSessionKey(sessionKey);
        setPhone(phone);
        setPaySecret(paySecret);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FxUserRecord
     */
    public FxUserRecord(com.iqexception.fxhelper.user.dal.generator.tables.pojos.FxUser value) {
        super(FxUser.FX_USER);

        if (value != null) {
            setUserId(value.getUserId());
            setNickName(value.getNickName());
            setAvatar(value.getAvatar());
            setOpenId(value.getOpenId());
            setUnionId(value.getUnionId());
            setSessionKey(value.getSessionKey());
            setPhone(value.getPhone());
            setPaySecret(value.getPaySecret());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
