/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.shop.dal.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxSerialNo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long shopId;
    private String serialNo;
    private LocalDateTime createdAt;

    public FxSerialNo() {}

    public FxSerialNo(FxSerialNo value) {
        this.id = value.id;
        this.shopId = value.shopId;
        this.serialNo = value.serialNo;
        this.createdAt = value.createdAt;
    }

    public FxSerialNo(
        Long id,
        Long shopId,
        String serialNo,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.shopId = shopId;
        this.serialNo = serialNo;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>fx.fx_serial_no.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>fx.fx_serial_no.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>fx.fx_serial_no.SHOP_ID</code>.
     */
    public Long getShopId() {
        return this.shopId;
    }

    /**
     * Setter for <code>fx.fx_serial_no.SHOP_ID</code>.
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * Getter for <code>fx.fx_serial_no.SERIAL_NO</code>.
     */
    public String getSerialNo() {
        return this.serialNo;
    }

    /**
     * Setter for <code>fx.fx_serial_no.SERIAL_NO</code>.
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * Getter for <code>fx.fx_serial_no.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>fx.fx_serial_no.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FxSerialNo other = (FxSerialNo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!this.shopId.equals(other.shopId))
            return false;
        if (this.serialNo == null) {
            if (other.serialNo != null)
                return false;
        }
        else if (!this.serialNo.equals(other.serialNo))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.serialNo == null) ? 0 : this.serialNo.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FxSerialNo (");

        sb.append(id);
        sb.append(", ").append(shopId);
        sb.append(", ").append(serialNo);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
