/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.resttemplate.pay.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InternalAcct2wxResult
 */
@JsonPropertyOrder({
  InternalAcct2wxResult.JSON_PROPERTY_PAY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:27:01.938116+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class InternalAcct2wxResult {
  public static final String JSON_PROPERTY_PAY_ID = "payId";
  @jakarta.annotation.Nonnull
  private Long payId;

  public InternalAcct2wxResult() {
  }

  public InternalAcct2wxResult payId(@jakarta.annotation.Nonnull Long payId) {
    
    this.payId = payId;
    return this;
  }

  /**
   * Get payId
   * @return payId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPayId() {
    return payId;
  }


  @JsonProperty(JSON_PROPERTY_PAY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayId(@jakarta.annotation.Nonnull Long payId) {
    this.payId = payId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalAcct2wxResult internalAcct2wxResult = (InternalAcct2wxResult) o;
    return Objects.equals(this.payId, internalAcct2wxResult.payId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalAcct2wxResult {\n");
    sb.append("    payId: ").append(toIndentedString(payId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

