/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.pay.dal.generator;


import com.iqexception.fxhelper.pay.dal.generator.tables.FxPayInfo;
import com.iqexception.fxhelper.pay.dal.generator.tables.records.FxPayInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FxPayInfoRecord> CONSTRAINT_2 = Internal.createUniqueKey(FxPayInfo.FX_PAY_INFO, DSL.name("CONSTRAINT_2"), new TableField[] { FxPayInfo.FX_PAY_INFO.ID }, true);
    public static final UniqueKey<FxPayInfoRecord> CONSTRAINT_2C = Internal.createUniqueKey(FxPayInfo.FX_PAY_INFO, DSL.name("CONSTRAINT_2C"), new TableField[] { FxPayInfo.FX_PAY_INFO.BIZ_ID }, true);
}
