/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.pay.dal.generator;


import com.iqexception.fxhelper.pay.dal.generator.tables.FxPayInfo;


/**
 * Convenience access to all tables in fx.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>fx.fx_pay_info</code>.
     */
    public static final FxPayInfo FX_PAY_INFO = FxPayInfo.FX_PAY_INFO;
}
