/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.account.dal.generator.tables;


import com.iqexception.fxhelper.account.dal.generator.Fx;
import com.iqexception.fxhelper.account.dal.generator.Indexes;
import com.iqexception.fxhelper.account.dal.generator.Keys;
import com.iqexception.fxhelper.account.dal.generator.tables.records.FxAccountRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxAccount extends TableImpl<FxAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fx.fx_account</code>
     */
    public static final FxAccount FX_ACCOUNT = new FxAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxAccountRecord> getRecordType() {
        return FxAccountRecord.class;
    }

    /**
     * The column <code>fx.fx_account.ACCOUNT_ID</code>.
     */
    public final TableField<FxAccountRecord, Long> ACCOUNT_ID = createField(DSL.name("ACCOUNT_ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>fx.fx_account.USER_ID</code>.
     */
    public final TableField<FxAccountRecord, Long> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>fx.fx_account.BALANCE</code>.
     */
    public final TableField<FxAccountRecord, BigDecimal> BALANCE = createField(DSL.name("BALANCE"), SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>fx.fx_account.STATUS</code>.
     */
    public final TableField<FxAccountRecord, Integer> STATUS = createField(DSL.name("STATUS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>fx.fx_account.CREATED_AT</code>.
     */
    public final TableField<FxAccountRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>fx.fx_account.UPDATED_AT</code>.
     */
    public final TableField<FxAccountRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FxAccount(Name alias, Table<FxAccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FxAccount(Name alias, Table<FxAccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fx.fx_account</code> table reference
     */
    public FxAccount(String alias) {
        this(DSL.name(alias), FX_ACCOUNT);
    }

    /**
     * Create an aliased <code>fx.fx_account</code> table reference
     */
    public FxAccount(Name alias) {
        this(alias, FX_ACCOUNT);
    }

    /**
     * Create a <code>fx.fx_account</code> table reference
     */
    public FxAccount() {
        this(DSL.name("fx_account"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fx.FX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FX_ACCOUNT_IDX_CREATED_AT, Indexes.FX_ACCOUNT_IDX_UPDATED_AT);
    }

    @Override
    public Identity<FxAccountRecord, Long> getIdentity() {
        return (Identity<FxAccountRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxAccountRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_1;
    }

    @Override
    public List<UniqueKey<FxAccountRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_1B);
    }

    @Override
    public FxAccount as(String alias) {
        return new FxAccount(DSL.name(alias), this);
    }

    @Override
    public FxAccount as(Name alias) {
        return new FxAccount(alias, this);
    }

    @Override
    public FxAccount as(Table<?> alias) {
        return new FxAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAccount rename(String name) {
        return new FxAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAccount rename(Name name) {
        return new FxAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAccount rename(Table<?> name) {
        return new FxAccount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxAccount where(Condition condition) {
        return new FxAccount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxAccount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxAccount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxAccount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxAccount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxAccount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxAccount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FxAccount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxAccount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FxAccount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
