/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.jdk.async.user.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.iqexception.fxhelper.client.jdk.async.user.ApiClient;
/**
 * InternalChangePaySecretRequest
 */
@JsonPropertyOrder({
  InternalChangePaySecretRequest.JSON_PROPERTY_USER_ID,
  InternalChangePaySecretRequest.JSON_PROPERTY_PAY_SECRET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:29:40.601017+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class InternalChangePaySecretRequest {
  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nonnull
  private Long userId;

  public static final String JSON_PROPERTY_PAY_SECRET = "paySecret";
  @jakarta.annotation.Nonnull
  private String paySecret;

  public InternalChangePaySecretRequest() { 
  }

  public InternalChangePaySecretRequest userId(@jakarta.annotation.Nonnull Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Long userId) {
    this.userId = userId;
  }


  public InternalChangePaySecretRequest paySecret(@jakarta.annotation.Nonnull String paySecret) {
    this.paySecret = paySecret;
    return this;
  }

  /**
   * Get paySecret
   * @return paySecret
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAY_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPaySecret() {
    return paySecret;
  }


  @JsonProperty(JSON_PROPERTY_PAY_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaySecret(@jakarta.annotation.Nonnull String paySecret) {
    this.paySecret = paySecret;
  }


  /**
   * Return true if this InternalChangePaySecretRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalChangePaySecretRequest internalChangePaySecretRequest = (InternalChangePaySecretRequest) o;
    return Objects.equals(this.userId, internalChangePaySecretRequest.userId) &&
        Objects.equals(this.paySecret, internalChangePaySecretRequest.paySecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, paySecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalChangePaySecretRequest {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    paySecret: ").append(toIndentedString(paySecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `userId` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format("%suserId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserId()))));
    }

    // add `paySecret` to the URL query string
    if (getPaySecret() != null) {
      joiner.add(String.format("%spaySecret%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaySecret()))));
    }

    return joiner.toString();
  }
}

