/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.webclient.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.iqexception.fxhelper.client.webclient.user.model.UserInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InternalGetUserListResult
 */
@JsonPropertyOrder({
  InternalGetUserListResult.JSON_PROPERTY_USER_LIST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:28:57.577124+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class InternalGetUserListResult {
  public static final String JSON_PROPERTY_USER_LIST = "userList";
  @jakarta.annotation.Nullable
  private List<UserInfo> userList = new ArrayList<>();

  public InternalGetUserListResult() {
  }

  public InternalGetUserListResult userList(@jakarta.annotation.Nullable List<UserInfo> userList) {
    
    this.userList = userList;
    return this;
  }

  public InternalGetUserListResult addUserListItem(UserInfo userListItem) {
    if (this.userList == null) {
      this.userList = new ArrayList<>();
    }
    this.userList.add(userListItem);
    return this;
  }

  /**
   * Get userList
   * @return userList
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UserInfo> getUserList() {
    return userList;
  }


  @JsonProperty(JSON_PROPERTY_USER_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserList(@jakarta.annotation.Nullable List<UserInfo> userList) {
    this.userList = userList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalGetUserListResult internalGetUserListResult = (InternalGetUserListResult) o;
    return Objects.equals(this.userList, internalGetUserListResult.userList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalGetUserListResult {\n");
    sb.append("    userList: ").append(toIndentedString(userList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

