/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.iqexception.fxhelper.client.webclient.user.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserLoginResult
 */
@JsonPropertyOrder({
  UserLoginResult.JSON_PROPERTY_TOKEN,
  UserLoginResult.JSON_PROPERTY_NEW_USER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:28:57.577124+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class UserLoginResult {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nonnull
  private String token;

  public static final String JSON_PROPERTY_NEW_USER = "newUser";
  @jakarta.annotation.Nonnull
  private Boolean newUser;

  public UserLoginResult() {
  }

  public UserLoginResult token(@jakarta.annotation.Nonnull String token) {
    
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(@jakarta.annotation.Nonnull String token) {
    this.token = token;
  }

  public UserLoginResult newUser(@jakarta.annotation.Nonnull Boolean newUser) {
    
    this.newUser = newUser;
    return this;
  }

  /**
   * Get newUser
   * @return newUser
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NEW_USER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getNewUser() {
    return newUser;
  }


  @JsonProperty(JSON_PROPERTY_NEW_USER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewUser(@jakarta.annotation.Nonnull Boolean newUser) {
    this.newUser = newUser;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserLoginResult userLoginResult = (UserLoginResult) o;
    return Objects.equals(this.token, userLoginResult.token) &&
        Objects.equals(this.newUser, userLoginResult.newUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, newUser);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserLoginResult {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    newUser: ").append(toIndentedString(newUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

