/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FxWxMessage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String openId;
    private String templateId;
    private String page;
    private String msgBody;
    private Integer status;
    private String failMsg;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public FxWxMessage() {}

    public FxWxMessage(FxWxMessage value) {
        this.id = value.id;
        this.openId = value.openId;
        this.templateId = value.templateId;
        this.page = value.page;
        this.msgBody = value.msgBody;
        this.status = value.status;
        this.failMsg = value.failMsg;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public FxWxMessage(
        Long id,
        String openId,
        String templateId,
        String page,
        String msgBody,
        Integer status,
        String failMsg,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.openId = openId;
        this.templateId = templateId;
        this.page = page;
        this.msgBody = msgBody;
        this.status = status;
        this.failMsg = failMsg;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>fx.fx_wx_message.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>fx.fx_wx_message.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>fx.fx_wx_message.OPEN_ID</code>.
     */
    public String getOpenId() {
        return this.openId;
    }

    /**
     * Setter for <code>fx.fx_wx_message.OPEN_ID</code>.
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * Getter for <code>fx.fx_wx_message.TEMPLATE_ID</code>.
     */
    public String getTemplateId() {
        return this.templateId;
    }

    /**
     * Setter for <code>fx.fx_wx_message.TEMPLATE_ID</code>.
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * Getter for <code>fx.fx_wx_message.PAGE</code>.
     */
    public String getPage() {
        return this.page;
    }

    /**
     * Setter for <code>fx.fx_wx_message.PAGE</code>.
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * Getter for <code>fx.fx_wx_message.MSG_BODY</code>.
     */
    public String getMsgBody() {
        return this.msgBody;
    }

    /**
     * Setter for <code>fx.fx_wx_message.MSG_BODY</code>.
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }

    /**
     * Getter for <code>fx.fx_wx_message.STATUS</code>.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>fx.fx_wx_message.STATUS</code>.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * Getter for <code>fx.fx_wx_message.FAIL_MSG</code>.
     */
    public String getFailMsg() {
        return this.failMsg;
    }

    /**
     * Setter for <code>fx.fx_wx_message.FAIL_MSG</code>.
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg;
    }

    /**
     * Getter for <code>fx.fx_wx_message.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>fx.fx_wx_message.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>fx.fx_wx_message.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>fx.fx_wx_message.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FxWxMessage other = (FxWxMessage) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.openId == null) {
            if (other.openId != null)
                return false;
        }
        else if (!this.openId.equals(other.openId))
            return false;
        if (this.templateId == null) {
            if (other.templateId != null)
                return false;
        }
        else if (!this.templateId.equals(other.templateId))
            return false;
        if (this.page == null) {
            if (other.page != null)
                return false;
        }
        else if (!this.page.equals(other.page))
            return false;
        if (this.msgBody == null) {
            if (other.msgBody != null)
                return false;
        }
        else if (!this.msgBody.equals(other.msgBody))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.failMsg == null) {
            if (other.failMsg != null)
                return false;
        }
        else if (!this.failMsg.equals(other.failMsg))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.openId == null) ? 0 : this.openId.hashCode());
        result = prime * result + ((this.templateId == null) ? 0 : this.templateId.hashCode());
        result = prime * result + ((this.page == null) ? 0 : this.page.hashCode());
        result = prime * result + ((this.msgBody == null) ? 0 : this.msgBody.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.failMsg == null) ? 0 : this.failMsg.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FxWxMessage (");

        sb.append(id);
        sb.append(", ").append(openId);
        sb.append(", ").append(templateId);
        sb.append(", ").append(page);
        sb.append(", ").append(msgBody);
        sb.append(", ").append(status);
        sb.append(", ").append(failMsg);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
