/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator.tables.daos;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMessage;
import com.iqexception.fxhelper.misc.dal.generator.tables.records.FxWxMessageRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxWxMessageDao extends DAOImpl<FxWxMessageRecord, com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage, Long> {

    /**
     * Create a new FxWxMessageDao without any configuration
     */
    public FxWxMessageDao() {
        super(FxWxMessage.FX_WX_MESSAGE, com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage.class);
    }

    /**
     * Create a new FxWxMessageDao with an attached configuration
     */
    @Autowired
    public FxWxMessageDao(Configuration configuration) {
        super(FxWxMessage.FX_WX_MESSAGE, com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchById(Long... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage fetchOneById(Long value) {
        return fetchOne(FxWxMessage.FX_WX_MESSAGE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchOptionalById(Long value) {
        return fetchOptional(FxWxMessage.FX_WX_MESSAGE.ID, value);
    }

    /**
     * Fetch records that have <code>OPEN_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfOpenId(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.OPEN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>OPEN_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByOpenId(String... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.OPEN_ID, values);
    }

    /**
     * Fetch records that have <code>TEMPLATE_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfTemplateId(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.TEMPLATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TEMPLATE_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByTemplateId(String... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.TEMPLATE_ID, values);
    }

    /**
     * Fetch records that have <code>PAGE BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfPage(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.PAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PAGE IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByPage(String... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.PAGE, values);
    }

    /**
     * Fetch records that have <code>MSG_BODY BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfMsgBody(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.MSG_BODY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>MSG_BODY IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByMsgBody(String... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.MSG_BODY, values);
    }

    /**
     * Fetch records that have <code>STATUS BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByStatus(Integer... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.STATUS, values);
    }

    /**
     * Fetch records that have <code>FAIL_MSG BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfFailMsg(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.FAIL_MSG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>FAIL_MSG IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByFailMsg(String... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.FAIL_MSG, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxWxMessage.FX_WX_MESSAGE.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMessage> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(FxWxMessage.FX_WX_MESSAGE.UPDATED_AT, values);
    }
}
