/*
 * This file is generated by jOOQ.
 */
package com.iqexception.fxhelper.misc.dal.generator.tables.daos;


import com.iqexception.fxhelper.misc.dal.generator.tables.FxWxMsgSubs;
import com.iqexception.fxhelper.misc.dal.generator.tables.records.FxWxMsgSubsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class FxWxMsgSubsDao extends DAOImpl<FxWxMsgSubsRecord, com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs, Long> {

    /**
     * Create a new FxWxMsgSubsDao without any configuration
     */
    public FxWxMsgSubsDao() {
        super(FxWxMsgSubs.FX_WX_MSG_SUBS, com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs.class);
    }

    /**
     * Create a new FxWxMsgSubsDao with an attached configuration
     */
    @Autowired
    public FxWxMsgSubsDao(Configuration configuration) {
        super(FxWxMsgSubs.FX_WX_MSG_SUBS, com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs.class, configuration);
    }

    @Override
    public Long getId(com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(FxWxMsgSubs.FX_WX_MSG_SUBS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchById(Long... values) {
        return fetch(FxWxMsgSubs.FX_WX_MSG_SUBS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs fetchOneById(Long value) {
        return fetchOne(FxWxMsgSubs.FX_WX_MSG_SUBS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public Optional<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchOptionalById(Long value) {
        return fetchOptional(FxWxMsgSubs.FX_WX_MSG_SUBS.ID, value);
    }

    /**
     * Fetch records that have <code>OPEN_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchRangeOfOpenId(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMsgSubs.FX_WX_MSG_SUBS.OPEN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>OPEN_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchByOpenId(String... values) {
        return fetch(FxWxMsgSubs.FX_WX_MSG_SUBS.OPEN_ID, values);
    }

    /**
     * Fetch records that have <code>TEMPLATE_ID BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchRangeOfTemplateId(String lowerInclusive, String upperInclusive) {
        return fetchRange(FxWxMsgSubs.FX_WX_MSG_SUBS.TEMPLATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TEMPLATE_ID IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchByTemplateId(String... values) {
        return fetch(FxWxMsgSubs.FX_WX_MSG_SUBS.TEMPLATE_ID, values);
    }

    /**
     * Fetch records that have <code>COUNT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchRangeOfCount(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FxWxMsgSubs.FX_WX_MSG_SUBS.COUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>COUNT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchByCount(Integer... values) {
        return fetch(FxWxMsgSubs.FX_WX_MSG_SUBS.COUNT, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxWxMsgSubs.FX_WX_MSG_SUBS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(FxWxMsgSubs.FX_WX_MSG_SUBS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FxWxMsgSubs.FX_WX_MSG_SUBS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.iqexception.fxhelper.misc.dal.generator.tables.pojos.FxWxMsgSubs> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(FxWxMsgSubs.FX_WX_MSG_SUBS.UPDATED_AT, values);
    }
}
