/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.iqexception.fxhelper.client.jdk.async.user.api;

import com.iqexception.fxhelper.client.jdk.async.user.ApiClient;
import com.iqexception.fxhelper.client.jdk.async.user.ApiException;
import com.iqexception.fxhelper.client.jdk.async.user.ApiResponse;
import com.iqexception.fxhelper.client.jdk.async.user.Configuration;
import com.iqexception.fxhelper.client.jdk.async.user.Pair;

import com.iqexception.fxhelper.client.jdk.async.user.model.BaseResponse;
import com.iqexception.fxhelper.client.jdk.async.user.model.InternalChangePaySecretRequest;
import com.iqexception.fxhelper.client.jdk.async.user.model.InternalCheckLoginRequest;
import com.iqexception.fxhelper.client.jdk.async.user.model.InternalGetUserListRequest;
import com.iqexception.fxhelper.client.jdk.async.user.model.InternalGetUserRequest;
import com.iqexception.fxhelper.client.jdk.async.user.model.InternalVerifyPaySecretRequest;
import com.iqexception.fxhelper.client.jdk.async.user.model.RequestUserLoginParam;
import com.iqexception.fxhelper.client.jdk.async.user.model.ResponseInternalCheckLoginResult;
import com.iqexception.fxhelper.client.jdk.async.user.model.ResponseInternalGetUserListResult;
import com.iqexception.fxhelper.client.jdk.async.user.model.ResponseInternalGetUserResult;
import com.iqexception.fxhelper.client.jdk.async.user.model.ResponseInternalVerifyPaySecretResult;
import com.iqexception.fxhelper.client.jdk.async.user.model.ResponseUserLoginResult;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

import java.util.concurrent.CompletableFuture;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-15T21:29:40.601017+08:00[Asia/Shanghai]", comments = "Generator version: 7.12.0")
public class UserApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public UserApi() {
    this(Configuration.getDefaultApiClient());
  }

  public UserApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  private ApiException getApiException(String operationId, HttpResponse<String> response) {
    String message = formatExceptionMessage(operationId, response.statusCode(), response.body());
    return new ApiException(response.statusCode(), message, response.headers(), response.body());
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * 
   * 
   * @param internalChangePaySecretRequest  (required)
   * @return CompletableFuture&lt;BaseResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<BaseResponse> internalChangePaySecret(InternalChangePaySecretRequest internalChangePaySecretRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalChangePaySecretRequestBuilder(internalChangePaySecretRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalChangePaySecret", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<BaseResponse>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
      });
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  /**
   * 
   * 
   * @param internalChangePaySecretRequest  (required)
   * @return CompletableFuture&lt;ApiResponse&lt;BaseResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ApiResponse<BaseResponse>> internalChangePaySecretWithHttpInfo(InternalChangePaySecretRequest internalChangePaySecretRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalChangePaySecretRequestBuilder(internalChangePaySecretRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (memberVarAsyncResponseInterceptor != null) {
              memberVarAsyncResponseInterceptor.accept(localVarResponse);
            }
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalChangePaySecret", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  new ApiResponse<BaseResponse>(
                      localVarResponse.statusCode(),
                      localVarResponse.headers().map(),
                      responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<BaseResponse>() {}))
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
        }
      );
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  private HttpRequest.Builder internalChangePaySecretRequestBuilder(InternalChangePaySecretRequest internalChangePaySecretRequest) throws ApiException {
    // verify the required parameter 'internalChangePaySecretRequest' is set
    if (internalChangePaySecretRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'internalChangePaySecretRequest' when calling internalChangePaySecret");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/internal/change_pay_secret";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(internalChangePaySecretRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param internalCheckLoginRequest  (required)
   * @return CompletableFuture&lt;ResponseInternalCheckLoginResult&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ResponseInternalCheckLoginResult> internalCheckLogin(InternalCheckLoginRequest internalCheckLoginRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalCheckLoginRequestBuilder(internalCheckLoginRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalCheckLogin", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalCheckLoginResult>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
      });
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  /**
   * 
   * 
   * @param internalCheckLoginRequest  (required)
   * @return CompletableFuture&lt;ApiResponse&lt;ResponseInternalCheckLoginResult&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ApiResponse<ResponseInternalCheckLoginResult>> internalCheckLoginWithHttpInfo(InternalCheckLoginRequest internalCheckLoginRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalCheckLoginRequestBuilder(internalCheckLoginRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (memberVarAsyncResponseInterceptor != null) {
              memberVarAsyncResponseInterceptor.accept(localVarResponse);
            }
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalCheckLogin", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  new ApiResponse<ResponseInternalCheckLoginResult>(
                      localVarResponse.statusCode(),
                      localVarResponse.headers().map(),
                      responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalCheckLoginResult>() {}))
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
        }
      );
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  private HttpRequest.Builder internalCheckLoginRequestBuilder(InternalCheckLoginRequest internalCheckLoginRequest) throws ApiException {
    // verify the required parameter 'internalCheckLoginRequest' is set
    if (internalCheckLoginRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'internalCheckLoginRequest' when calling internalCheckLogin");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/internal/check_login";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(internalCheckLoginRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param internalGetUserRequest  (required)
   * @return CompletableFuture&lt;ResponseInternalGetUserResult&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ResponseInternalGetUserResult> internalGet(InternalGetUserRequest internalGetUserRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalGetRequestBuilder(internalGetUserRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalGet", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalGetUserResult>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
      });
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  /**
   * 
   * 
   * @param internalGetUserRequest  (required)
   * @return CompletableFuture&lt;ApiResponse&lt;ResponseInternalGetUserResult&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ApiResponse<ResponseInternalGetUserResult>> internalGetWithHttpInfo(InternalGetUserRequest internalGetUserRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalGetRequestBuilder(internalGetUserRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (memberVarAsyncResponseInterceptor != null) {
              memberVarAsyncResponseInterceptor.accept(localVarResponse);
            }
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalGet", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  new ApiResponse<ResponseInternalGetUserResult>(
                      localVarResponse.statusCode(),
                      localVarResponse.headers().map(),
                      responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalGetUserResult>() {}))
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
        }
      );
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  private HttpRequest.Builder internalGetRequestBuilder(InternalGetUserRequest internalGetUserRequest) throws ApiException {
    // verify the required parameter 'internalGetUserRequest' is set
    if (internalGetUserRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'internalGetUserRequest' when calling internalGet");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/internal/get";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(internalGetUserRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param internalGetUserListRequest  (required)
   * @return CompletableFuture&lt;ResponseInternalGetUserListResult&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ResponseInternalGetUserListResult> internalGetUserList(InternalGetUserListRequest internalGetUserListRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalGetUserListRequestBuilder(internalGetUserListRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalGetUserList", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalGetUserListResult>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
      });
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  /**
   * 
   * 
   * @param internalGetUserListRequest  (required)
   * @return CompletableFuture&lt;ApiResponse&lt;ResponseInternalGetUserListResult&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ApiResponse<ResponseInternalGetUserListResult>> internalGetUserListWithHttpInfo(InternalGetUserListRequest internalGetUserListRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalGetUserListRequestBuilder(internalGetUserListRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (memberVarAsyncResponseInterceptor != null) {
              memberVarAsyncResponseInterceptor.accept(localVarResponse);
            }
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalGetUserList", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  new ApiResponse<ResponseInternalGetUserListResult>(
                      localVarResponse.statusCode(),
                      localVarResponse.headers().map(),
                      responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalGetUserListResult>() {}))
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
        }
      );
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  private HttpRequest.Builder internalGetUserListRequestBuilder(InternalGetUserListRequest internalGetUserListRequest) throws ApiException {
    // verify the required parameter 'internalGetUserListRequest' is set
    if (internalGetUserListRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'internalGetUserListRequest' when calling internalGetUserList");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/internal/get_user_list";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(internalGetUserListRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param internalVerifyPaySecretRequest  (required)
   * @return CompletableFuture&lt;ResponseInternalVerifyPaySecretResult&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ResponseInternalVerifyPaySecretResult> internalVerifyPaySecret(InternalVerifyPaySecretRequest internalVerifyPaySecretRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalVerifyPaySecretRequestBuilder(internalVerifyPaySecretRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalVerifyPaySecret", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalVerifyPaySecretResult>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
      });
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  /**
   * 
   * 
   * @param internalVerifyPaySecretRequest  (required)
   * @return CompletableFuture&lt;ApiResponse&lt;ResponseInternalVerifyPaySecretResult&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ApiResponse<ResponseInternalVerifyPaySecretResult>> internalVerifyPaySecretWithHttpInfo(InternalVerifyPaySecretRequest internalVerifyPaySecretRequest) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = internalVerifyPaySecretRequestBuilder(internalVerifyPaySecretRequest);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (memberVarAsyncResponseInterceptor != null) {
              memberVarAsyncResponseInterceptor.accept(localVarResponse);
            }
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("internalVerifyPaySecret", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  new ApiResponse<ResponseInternalVerifyPaySecretResult>(
                      localVarResponse.statusCode(),
                      localVarResponse.headers().map(),
                      responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseInternalVerifyPaySecretResult>() {}))
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
        }
      );
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  private HttpRequest.Builder internalVerifyPaySecretRequestBuilder(InternalVerifyPaySecretRequest internalVerifyPaySecretRequest) throws ApiException {
    // verify the required parameter 'internalVerifyPaySecretRequest' is set
    if (internalVerifyPaySecretRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'internalVerifyPaySecretRequest' when calling internalVerifyPaySecret");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/internal/verify_pay_secret";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(internalVerifyPaySecretRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param requestUserLoginParam  (required)
   * @return CompletableFuture&lt;ResponseUserLoginResult&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ResponseUserLoginResult> login(RequestUserLoginParam requestUserLoginParam) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = loginRequestBuilder(requestUserLoginParam);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("login", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseUserLoginResult>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
      });
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  /**
   * 
   * 
   * @param requestUserLoginParam  (required)
   * @return CompletableFuture&lt;ApiResponse&lt;ResponseUserLoginResult&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public CompletableFuture<ApiResponse<ResponseUserLoginResult>> loginWithHttpInfo(RequestUserLoginParam requestUserLoginParam) throws ApiException {
    try {
      HttpRequest.Builder localVarRequestBuilder = loginRequestBuilder(requestUserLoginParam);
      return memberVarHttpClient.sendAsync(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
            if (memberVarAsyncResponseInterceptor != null) {
              memberVarAsyncResponseInterceptor.accept(localVarResponse);
            }
            if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("login", localVarResponse));
            }
            try {
              String responseBody = localVarResponse.body();
              return CompletableFuture.completedFuture(
                  new ApiResponse<ResponseUserLoginResult>(
                      localVarResponse.statusCode(),
                      localVarResponse.headers().map(),
                      responseBody == null || responseBody.isBlank() ? null : memberVarObjectMapper.readValue(responseBody, new TypeReference<ResponseUserLoginResult>() {}))
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
        }
      );
    }
    catch (ApiException e) {
      return CompletableFuture.failedFuture(e);
    }
  }

  private HttpRequest.Builder loginRequestBuilder(RequestUserLoginParam requestUserLoginParam) throws ApiException {
    // verify the required parameter 'requestUserLoginParam' is set
    if (requestUserLoginParam == null) {
      throw new ApiException(400, "Missing the required parameter 'requestUserLoginParam' when calling login");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/login";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestUserLoginParam);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
